import { useState, useEffect, useCallback, useRef, Fragment } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import {
  DndContext,
  closestCenter,
  PointerSensor,
  useSensor,
  useSensors,
} from '@dnd-kit/core';
import type { DragEndEvent } from '@dnd-kit/core';
import {
  SortableContext,
  verticalListSortingStrategy,
  useSortable,
  arrayMove,
} from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import Nav from '../components/Nav';
import RadarChart from '../components/RadarChart';
import { getCurrentUser, getStudentData } from '../auth';

const API_BASE = (import.meta.env.VITE_API_URL as string) || 'https://app.lablinkinitiative.org';

// ─── Types ────────────────────────────────────────────────────────────────────

interface PathwayItem {
  id: string;
  title: string;
  short_name: string;
  description: string;
  career_field: string;
  entry_level: string | null;
  keywords: string[];
  usage_count: number;
  requirements?: Record<string, unknown>;
}

interface AssignedPathway {
  id: number;
  pathway_id: string;
  title: string;
  short_name: string;
  description: string;
  career_field: string;
  fit_score: number | null;
  fit_tier: 'high' | 'medium' | 'stretch' | null;
  notes: string | null;
  is_default: boolean;
  assigned_at: string;
  gap_analysis: { id: string; status: string; overall_match: number | null; summary: string | null } | null;
  mapped_programs_count: number;
}

interface SkillBreakdownItem {
  skill: string;
  studentLevel: number;
  requiredLevel: number;
  gap: number;
  status: 'meets' | 'partial' | 'gap';
  rationale?: string;
}

interface Recommendation {
  priority: 'high' | 'medium' | 'low';
  text: string;
  resource: string | null;
}

interface GapAnalysis {
  id: string;
  pathwayId: string;
  pathwayName: string;
  status: 'queued' | 'processing' | 'complete' | 'error';
  overallMatch: number | null;
  readinessLevel: string | null;
  summary: string | null;
  strengths: string[];
  gaps: string[];
  skillBreakdown: SkillBreakdownItem[];
  recommendations: Recommendation[];
  radarData: { axes: string[]; studentScores: number[]; requiredScores: number[] };
  timelineEst: string | null;
  autoGenerated: boolean;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function matchColor(pct: number | null) {
  if (pct === null) return 'var(--text-muted)';
  if (pct >= 70) return 'var(--success, #15803d)';
  if (pct >= 45) return 'var(--warning, #b45309)';
  return 'var(--error, #dc2626)';
}

function readinessLabel(level: string | null, pct: number | null): string {
  if (level === 'strong_candidate') return 'Strong candidate';
  if (level === 'ready') return 'Ready to apply';
  if (level === 'building') return 'Building readiness';
  if (level === 'early_stage') return 'Early stage — keep building';
  if (pct !== null) {
    if (pct >= 70) return 'Strong candidate';
    if (pct >= 45) return 'Building readiness';
    return 'Early stage — keep building';
  }
  return '';
}

// ─── Locked State ─────────────────────────────────────────────────────────────

function LockedState({ completeness }: { completeness: number }) {
  const needed = 60 - completeness;
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', padding: 'var(--sp-2xl) var(--sp-lg)' }}>
      <div style={{ width: 72, height: 72, borderRadius: '50%', background: 'var(--surface)', border: '2px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.75rem', marginBottom: 'var(--sp-md)', boxShadow: 'var(--shadow-sm)' }}>
        <span style={{ lineHeight: 1 }}>&#128274;</span>
      </div>
      <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 800, color: 'var(--text-strong)', fontFamily: 'Plus Jakarta Sans, sans-serif', marginBottom: '0.5rem' }}>
        Complete Your Profile to Unlock Pathways
      </h2>
      <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', lineHeight: 1.6, maxWidth: 420, marginBottom: 'var(--sp-lg)' }}>
        {needed > 0
          ? `You're ${completeness}% complete — add ${needed}% more and we'll automatically generate your personalized career pathways.`
          : 'Almost there! Finish your profile and your pathways will generate automatically.'}
      </p>
      <div style={{ width: '100%', maxWidth: 360, marginBottom: 'var(--sp-lg)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.375rem' }}>
          <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', fontWeight: 600 }}>Profile progress</span>
          <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: 'var(--brand-700)' }}>{completeness}% / 60% needed</span>
        </div>
        <div style={{ height: 10, background: 'var(--surface-2)', borderRadius: 99, overflow: 'hidden' }}>
          <div style={{ height: '100%', width: `${Math.min(100, (completeness / 60) * 100)}%`, background: completeness >= 40 ? 'var(--brand-500)' : 'var(--brand-300)', borderRadius: 99, transition: 'width 0.4s ease' }} />
        </div>
      </div>
      <div style={{ display: 'flex', gap: 'var(--sp-sm)', flexWrap: 'wrap', justifyContent: 'center' }}>
        <Link to="/profile" className="btn btn-primary">Update Profile →</Link>
        <Link to="/resume" className="btn btn-secondary">Upload Resume</Link>
      </div>
    </div>
  );
}

// ─── Gap Analysis Panel ───────────────────────────────────────────────────────

interface AnalysisPanelProps {
  analysis: GapAnalysis;
  pathwayTitle: string;
  onRefresh: (pathwayId: string) => void;
  pathwayId: string;
}

function AnalysisPanel({ analysis, pathwayTitle, onRefresh, pathwayId }: AnalysisPanelProps) {
  if (analysis.status === 'queued' || analysis.status === 'processing') {
    return (
      <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-2xl)' }}>
        <div style={{ fontSize: '2rem', marginBottom: 'var(--sp-md)' }}>🧠</div>
        <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-lg)', fontWeight: 700, marginBottom: '0.5rem' }}>Analyzing your profile…</h3>
        <p style={{ color: 'var(--text-muted)', fontSize: 'var(--text-sm)', marginBottom: 'var(--sp-lg)' }}>
          Claude is reading your full profile and reasoning about your readiness for <strong>{pathwayTitle}</strong>. Usually takes 30–60 seconds.
        </p>
        <div style={{ height: 6, background: 'var(--surface-2)', borderRadius: 99, overflow: 'hidden', maxWidth: 300, margin: '0 auto var(--sp-md)' }}>
          <div style={{ height: '100%', width: '60%', background: 'var(--brand-500)', borderRadius: 99, animation: 'gapPulse 2s ease-in-out infinite' }} />
        </div>
        <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)' }}>Status: {analysis.status}</p>
      </div>
    );
  }

  if (analysis.status === 'error') {
    return (
      <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-xl)' }}>
        <div style={{ fontSize: '1.5rem', marginBottom: '0.5rem' }}>⚠️</div>
        <p style={{ color: 'var(--error, #dc2626)', fontWeight: 600, marginBottom: '0.5rem' }}>Analysis failed</p>
        <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', marginBottom: 'var(--sp-md)' }}>{analysis.error}</p>
        <button className="btn btn-primary btn-sm" onClick={() => onRefresh(pathwayId)}>Try Again</button>
      </div>
    );
  }

  return (
    <div>
      {/* Summary */}
      <div className="card" style={{ marginBottom: 'var(--sp-md)', background: 'linear-gradient(135deg, rgba(154,184,46,0.06) 0%, var(--surface) 60%)' }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
          <div style={{ textAlign: 'center', flexShrink: 0 }}>
            <div style={{ fontSize: '2.5rem', fontWeight: 800, color: matchColor(analysis.overallMatch), lineHeight: 1 }}>{analysis.overallMatch}%</div>
            <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', marginTop: '0.25rem' }}>Match</div>
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '0.25rem' }}>
              <div style={{ fontSize: 'var(--text-xs)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: matchColor(analysis.overallMatch) }}>
                {readinessLabel(analysis.readinessLevel, analysis.overallMatch)}
              </div>
              {analysis.autoGenerated && <span style={{ background: 'var(--surface-2)', borderRadius: 4, padding: '1px 5px', fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>auto</span>}
            </div>
            {analysis.timelineEst && (
              <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', wordBreak: 'break-word', lineHeight: 1.5 }}>
                <strong>Timeline:</strong> {analysis.timelineEst}
              </div>
            )}
          </div>
        </div>
        <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-default)', lineHeight: 1.65 }}>{analysis.summary}</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.5fr', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
        {(analysis.strengths || []).length > 0 && (
          <div className="card">
            <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--success, #15803d)', marginBottom: 'var(--sp-sm)' }}>✓ Strengths</h3>
            <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.375rem' }}>
              {(analysis.strengths || []).map((s, i) => <li key={i} style={{ fontSize: 'var(--text-xs)', color: 'var(--text-default)', lineHeight: 1.5 }}>{s}</li>)}
            </ul>
          </div>
        )}
        {(analysis.gaps || []).length > 0 && (
          <div className="card">
            <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--error, #dc2626)', marginBottom: 'var(--sp-sm)' }}>↑ Areas to Develop</h3>
            <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.375rem' }}>
              {(analysis.gaps || []).map((g, i) => <li key={i} style={{ fontSize: 'var(--text-xs)', color: 'var(--text-default)', lineHeight: 1.5 }}>{g}</li>)}
            </ul>
          </div>
        )}
      </div>

      {(analysis.radarData?.axes?.length > 2 || (analysis.skillBreakdown || []).length > 0) && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.5fr', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
          {analysis.radarData?.axes?.length > 2 && (
            <div className="card">
              <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--text-muted)', marginBottom: 'var(--sp-sm)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Skills Radar</h3>
              <RadarChart axes={analysis.radarData.axes} studentScores={analysis.radarData.studentScores} requiredScores={analysis.radarData.requiredScores} />
            </div>
          )}
          {(analysis.skillBreakdown || []).length > 0 && (
            <div className="card">
              <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--text-strong)', marginBottom: 'var(--sp-sm)' }}>Skill Breakdown</h3>
              <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr auto auto', gap: '0.4rem 0.75rem', alignItems: 'center', fontSize: '0.7rem' }}>
                {['Skill', 'Level', 'Req', 'Status'].map(h => <div key={h} style={{ fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{h}</div>)}
                {(analysis.skillBreakdown || []).slice(0, 8).map((item, i) => (
                  <Fragment key={i}>
                    <div style={{ color: 'var(--text-default)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 130 }} title={item.skill}>
                      {item.skill.length > 22 ? item.skill.slice(0, 20) + '…' : item.skill}
                    </div>
                    <div style={{ height: 7, background: 'var(--surface-2)', borderRadius: 99, overflow: 'hidden' }}>
                      <div style={{ height: '100%', width: `${Math.round((item.studentLevel || 0) * 100)}%`, background: item.status === 'meets' ? 'var(--success, #15803d)' : item.status === 'partial' ? 'var(--warning, #b45309)' : 'var(--error, #dc2626)', borderRadius: 99 }} />
                    </div>
                    <div style={{ color: 'var(--text-muted)', textAlign: 'center' }}>{Math.round((item.requiredLevel || 0) * 100)}%</div>
                    <div style={{ fontSize: '0.6rem', fontWeight: 700, textTransform: 'capitalize', color: item.status === 'meets' ? 'var(--success, #15803d)' : item.status === 'partial' ? 'var(--warning, #b45309)' : 'var(--error, #dc2626)' }}>
                      {item.status}
                    </div>
                  </Fragment>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {(analysis.recommendations || []).length > 0 && (
        <div className="card" style={{ marginBottom: 'var(--sp-md)' }}>
          <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--text-strong)', marginBottom: 'var(--sp-md)' }}>Recommendations</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-sm)' }}>
            {(analysis.recommendations || []).map((rec, i) => (
              <div key={i} style={{ display: 'flex', gap: '0.75rem', padding: 'var(--sp-sm)', background: rec.priority === 'high' ? 'rgba(220,38,38,0.05)' : rec.priority === 'medium' ? 'rgba(251,191,36,0.08)' : 'var(--surface)', borderRadius: 'var(--radius-md)', border: `1px solid ${rec.priority === 'high' ? 'rgba(185,28,28,0.12)' : rec.priority === 'medium' ? 'rgba(180,83,9,0.12)' : 'var(--border)'}` }}>
                <div style={{ width: 20, height: 20, borderRadius: '50%', flexShrink: 0, background: rec.priority === 'high' ? 'var(--error, #dc2626)' : rec.priority === 'medium' ? 'var(--warning, #b45309)' : 'var(--text-faint)', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.55rem', fontWeight: 800, textTransform: 'uppercase', marginTop: '0.125rem' }}>
                  {rec.priority[0].toUpperCase()}
                </div>
                <div>
                  <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-default)', lineHeight: 1.55 }}>{rec.text}</p>
                  {rec.resource && <a href={rec.resource} target="_blank" rel="noopener noreferrer" style={{ fontSize: 'var(--text-xs)', color: 'var(--brand-700)', textDecoration: 'underline', marginTop: '0.25rem', display: 'inline-block' }}>Learn more ↗</a>}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div style={{ marginTop: 'var(--sp-sm)', display: 'flex', gap: 'var(--sp-sm)', alignItems: 'center', flexWrap: 'wrap' }}>
        <button onClick={() => onRefresh(pathwayId)} className="btn btn-ghost btn-sm">↺ Re-run analysis</button>
        <Link to="/profile" className="btn btn-ghost btn-sm">Update skills →</Link>
        <Link to={`/opportunities?pathway=${pathwayId}`} className="btn btn-ghost btn-sm">Browse programs →</Link>
        <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)' }}>
          {analysis.updatedAt ? `Last run: ${new Date(analysis.updatedAt).toLocaleDateString()}` : ''}
        </span>
      </div>
    </div>
  );
}

// ─── Sidebar Item (unassigned — plain button) ─────────────────────────────────

interface SidebarItemProps {
  pathwayId: string;
  label: string;
  isSelected: boolean;
  isAssigned: boolean;
  matchScore?: number | null;
  fitScore?: number | null;
  onClick: () => void;
}

function SidebarItem({ pathwayId: _pathwayId, label, isSelected, isAssigned, matchScore, fitScore, onClick }: SidebarItemProps) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        width: '100%',
        textAlign: 'left',
        padding: '0.5rem 0.625rem',
        borderRadius: 'var(--radius-md)',
        border: isSelected ? '1px solid var(--brand-500)' : '1px solid transparent',
        background: isSelected ? 'rgba(154,184,46,0.08)' : 'transparent',
        cursor: 'pointer',
        transition: 'background 0.12s, border-color 0.12s',
        opacity: isAssigned ? 1 : 0.55,
        minWidth: 0,
      }}
      onMouseEnter={(e) => { if (!isSelected) (e.currentTarget as HTMLButtonElement).style.background = 'var(--surface)'; }}
      onMouseLeave={(e) => { if (!isSelected) (e.currentTarget as HTMLButtonElement).style.background = 'transparent'; }}
    >
      <span style={{ fontSize: '0.6rem', color: isAssigned ? 'var(--brand-500)' : 'var(--text-faint)', flexShrink: 0, lineHeight: 1 }}>●</span>
      <span style={{
        fontSize: 'var(--text-xs)',
        fontWeight: isSelected ? 700 : isAssigned ? 600 : 400,
        color: isSelected ? 'var(--brand-700)' : isAssigned ? 'var(--text-strong)' : 'var(--text-muted)',
        overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1,
      }}>
        {label}
      </span>
      {isAssigned && (matchScore != null || fitScore != null) && (
        <span style={{ fontSize: '0.65rem', fontWeight: 700, color: matchScore != null ? matchColor(matchScore) : 'var(--text-muted)', flexShrink: 0 }}>
          {matchScore != null ? `${matchScore}%` : fitScore != null ? `${fitScore}%` : ''}
        </span>
      )}
    </button>
  );
}

// ─── Sortable Sidebar Item (assigned — full-card draggable) ───────────────────

interface SortableSidebarItemProps {
  pathwayId: string;
  label: string;
  isSelected: boolean;
  matchScore?: number | null;
  fitScore?: number | null;
  onClick: () => void;
  onRemove: (pathwayId: string) => void;
}

function SortableSidebarItem({ pathwayId, label, isSelected, matchScore, fitScore, onClick, onRemove }: SortableSidebarItemProps) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: pathwayId });
  const [hovered, setHovered] = useState(false);

  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition: transition ?? 'transform 200ms cubic-bezier(0.25, 1, 0.5, 1)',
    opacity: isDragging ? 0.45 : 1,
    boxShadow: isDragging ? '0 6px 20px rgba(0,0,0,0.18)' : 'none',
    zIndex: isDragging ? 999 : undefined,
    display: 'flex',
    alignItems: 'center',
    borderRadius: 'var(--radius-md)',
    userSelect: 'none',
    touchAction: 'none',
    cursor: isDragging ? 'grabbing' : 'grab',
    border: isSelected ? '1px solid var(--brand-500)' : '1px solid transparent',
    background: isSelected ? 'rgba(154,184,46,0.08)' : hovered && !isDragging ? 'var(--surface)' : 'transparent',
    padding: '0.5rem 0.375rem',
    gap: '0.375rem',
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      {...attributes}
      {...listeners}
      onClick={onClick}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {/* Drag hint — visual only, no pointer events */}
      <span style={{
        color: 'var(--text-faint)',
        fontSize: '0.7rem',
        flexShrink: 0,
        lineHeight: 1,
        opacity: hovered ? 0.5 : 0.2,
        transition: 'opacity 0.15s',
        pointerEvents: 'none',
      }}>⠿</span>
      <span style={{ fontSize: '0.6rem', color: 'var(--brand-500)', flexShrink: 0, lineHeight: 1, pointerEvents: 'none' }}>●</span>
      <span style={{
        fontSize: 'var(--text-xs)',
        fontWeight: isSelected ? 700 : 600,
        color: isSelected ? 'var(--brand-700)' : 'var(--text-strong)',
        overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1,
        pointerEvents: 'none',
      }}>
        {label}
      </span>
      {(matchScore != null || fitScore != null) && (
        <span style={{ fontSize: '0.65rem', fontWeight: 700, color: matchScore != null ? matchColor(matchScore) : 'var(--text-muted)', flexShrink: 0, pointerEvents: 'none' }}>
          {matchScore != null ? `${matchScore}%` : fitScore != null ? `${fitScore}%` : ''}
        </span>
      )}
      {/* Remove button — stopPropagation prevents drag and click-select */}
      <button
        type="button"
        onPointerDown={e => e.stopPropagation()}
        onClick={e => { e.stopPropagation(); onRemove(pathwayId); }}
        style={{
          opacity: hovered && !isDragging ? 0.55 : 0,
          transition: 'opacity 0.15s',
          flexShrink: 0,
          background: 'transparent',
          border: 'none',
          cursor: 'pointer',
          color: 'var(--text-faint)',
          fontSize: '0.7rem',
          padding: '2px 5px',
          lineHeight: 1,
          borderRadius: 'var(--radius-sm)',
        }}
        title="Remove from My Pathways"
      >
        ✕
      </button>
    </div>
  );
}

// ─── Right Panel: Unassigned Pathway ─────────────────────────────────────────

interface UnassignedPanelProps {
  pathway: PathwayItem;
  token: string | null;
  onRunAnalysis: (pathwayId: string) => void;
  onSave: (pathwayId: string) => void;
  hasAnalysis: boolean;
  runningAnalysis: boolean;
}

function UnassignedPanel({ pathway, onRunAnalysis, onSave, hasAnalysis, runningAnalysis }: UnassignedPanelProps) {
  const keywords = Array.isArray(pathway.keywords) ? pathway.keywords : (typeof pathway.keywords === 'string' ? (pathway.keywords as string).split(',').map((k: string) => k.trim()) : []);

  return (
    <div>
      <div className="card" style={{ marginBottom: 'var(--sp-md)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.375rem', marginBottom: 'var(--sp-sm)' }}>
              <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: 'var(--brand-700)', background: 'var(--brand-50)', borderRadius: 'var(--radius-sm)', padding: '2px 8px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                {pathway.career_field}
              </span>
              {pathway.entry_level && (
                <span style={{ fontSize: 'var(--text-xs)', fontWeight: 600, color: 'var(--text-muted)', background: 'var(--surface-2)', borderRadius: 'var(--radius-sm)', padding: '2px 6px' }}>
                  {pathway.entry_level}
                </span>
              )}
            </div>
            <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', lineHeight: 1.6 }}>{pathway.description}</p>
            {keywords.length > 0 && (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.25rem', marginTop: 'var(--sp-sm)' }}>
                {keywords.slice(0, 6).map((kw: string) => (
                  <span key={kw} style={{ fontSize: '0.7rem', color: 'var(--text-faint)', background: 'var(--surface-2)', borderRadius: 'var(--radius-sm)', padding: '2px 6px' }}>{kw}</span>
                ))}
              </div>
            )}
          </div>
        </div>

        <div style={{ display: 'flex', gap: 'var(--sp-sm)', flexWrap: 'wrap', alignItems: 'center' }}>
          <button
            className="btn btn-primary btn-sm"
            onClick={() => onRunAnalysis(pathway.id)}
            disabled={runningAnalysis}
          >
            {runningAnalysis ? 'Starting…' : hasAnalysis ? 'Re-run Analysis' : '▶ Run Gap Analysis'}
          </button>
          <button
            type="button"
            onClick={() => onSave(pathway.id)}
            style={{ fontSize: 'var(--text-xs)', fontWeight: 600, padding: '5px 10px', borderRadius: 'var(--radius-sm)', border: '1px solid var(--brand-300)', background: 'var(--brand-50)', color: 'var(--brand-700)', cursor: 'pointer', whiteSpace: 'nowrap' }}
          >
            + Save to My Pathways
          </button>
        </div>
      </div>

      {!hasAnalysis && (
        <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-xl)', color: 'var(--text-muted)' }}>
          <div style={{ fontSize: '2rem', marginBottom: 'var(--sp-md)', opacity: 0.4 }}>🧠</div>
          <p style={{ fontSize: 'var(--text-sm)', marginBottom: 'var(--sp-md)' }}>No analysis yet for this pathway.</p>
          <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)' }}>Run a gap analysis to see how ready you are and get personalized recommendations.</p>
        </div>
      )}
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function PathwayDashboard() {
  const user = getCurrentUser()!;
  useNavigate();
  const [searchParams] = useSearchParams();
  const token = localStorage.getItem('cdp_token');

  const student = getStudentData(user.uid);
  const completeness = student?.profileCompleteness || 0;
  const isLocked = completeness < 60;

  // Data state
  const [allPathways, setAllPathways] = useState<PathwayItem[]>([]);
  const [assignedPathways, setAssignedPathways] = useState<AssignedPathway[]>([]);
  const [analyses, setAnalyses] = useState<GapAnalysis[]>([]);

  // Loading state
  const [loadingPathways, setLoadingPathways] = useState(true);
  const [loadingAssigned, setLoadingAssigned] = useState(true);
  const [loadingAnalyses, setLoadingAnalyses] = useState(true);

  // Generation state (initial 3 pathways)
  const [generating, setGenerating] = useState(false);
  const [generationJobId, setGenerationJobId] = useState<string | null>(null);
  const [generationError, setGenerationError] = useState<string | null>(null);
  const [justGenerated, setJustGenerated] = useState(false);
  const autoTriggeredRef = useRef(false);

  // Analysis state
  const [runningAnalysis, setRunningAnalysis] = useState(false);
  const [analysisPollingId, setAnalysisPollingId] = useState<string | null>(null);
  const [runError, setRunError] = useState<string | null>(null);

  // UI state
  const [selectedId, setSelectedId] = useState<string | null>(searchParams.get('selected'));
  const [searchQuery, setSearchQuery] = useState('');

  // Redirect from old /pathway/:id route
  useEffect(() => {
    const fromId = searchParams.get('selected');
    if (fromId) setSelectedId(fromId);
  }, [searchParams]);

  // Load all pathways
  useEffect(() => {
    if (isLocked) { setLoadingPathways(false); return; }
    fetch(`${API_BASE}/api/cdp/pathways?limit=100`, {
      headers: { Authorization: `Bearer ${token}` },
    }).then(r => r.json()).then(d => {
      if (d.ok) setAllPathways(d.pathways || []);
    }).catch(() => {}).finally(() => setLoadingPathways(false));
  }, [token, isLocked]);

  // Load assigned pathways
  const loadAssigned = useCallback(async () => {
    if (isLocked) { setLoadingAssigned(false); return; }
    try {
      const res = await fetch(`${API_BASE}/api/cdp/students/me/pathways`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.ok) setAssignedPathways(data.pathways || []);
    } catch {}
    setLoadingAssigned(false);
  }, [token, isLocked]);

  useEffect(() => { loadAssigned(); }, [loadAssigned]);

  // Load gap analyses
  const loadAnalyses = useCallback(async () => {
    if (isLocked) { setLoadingAnalyses(false); return; }
    try {
      const res = await fetch(`${API_BASE}/api/cdp/gap-analyses`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.ok) {
        const list = data.analyses || [];
        setAnalyses(list);
        // Resume polling for any in-progress analysis from a previous session
        const inProgress = list.find(
          (a: { status: string; id: string }) => a.status === 'queued' || a.status === 'processing'
        );
        if (inProgress) setAnalysisPollingId(inProgress.id);
        // Fetch full detail for completed analyses (list endpoint returns minimal data)
        const completed = list.filter((a: { status: string; id: string }) => a.status === 'complete');
        for (const a of completed) {
          fetch(`${API_BASE}/api/cdp/gap-analysis/${a.id}`, { headers: { Authorization: `Bearer ${token}` } })
            .then(r => r.json())
            .then(d => {
              if (d.ok) setAnalyses(prev => prev.map(x => x.id === a.id ? d.analysis : x));
            })
            .catch(() => {});
        }
      }
    } catch {}
    setLoadingAnalyses(false);
  }, [token, isLocked]);

  useEffect(() => { loadAnalyses(); }, [loadAnalyses]);

  // Auto-select first assigned pathway when data loads
  useEffect(() => {
    if (!selectedId && assignedPathways.length > 0 && !loadingAssigned) {
      setSelectedId(assignedPathways[0].pathway_id);
    }
  }, [assignedPathways, loadingAssigned, selectedId]);

  // Auto-trigger initial generation if profile >= 60% and no pathways
  useEffect(() => {
    if (!loadingAssigned && !isLocked && assignedPathways.length === 0 && !generating && !generationError && !autoTriggeredRef.current) {
      autoTriggeredRef.current = true;
      handleGenerate();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loadingAssigned, isLocked, assignedPathways.length, generating, generationError]);

  // Poll generation job
  useEffect(() => {
    if (!generationJobId) return;
    const interval = setInterval(async () => {
      try {
        const res = await fetch(`${API_BASE}/api/cdp/students/me/pathways/status/${generationJobId}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        if (data.status === 'complete') {
          await loadAssigned();
          await loadAnalyses();
          setGenerating(false);
          setGenerationJobId(null);
          setJustGenerated(true);
          clearInterval(interval);
        } else if (data.status === 'error') {
          setGenerationError(data.error || 'Pathway generation failed. Please try again.');
          setGenerating(false);
          setGenerationJobId(null);
          clearInterval(interval);
        }
      } catch {}
    }, 3000);
    return () => clearInterval(interval);
  }, [generationJobId, token, loadAssigned, loadAnalyses]);

  // Poll gap analysis
  useEffect(() => {
    if (!analysisPollingId) return;
    const interval = setInterval(async () => {
      try {
        const res = await fetch(`${API_BASE}/api/cdp/gap-analysis/status/${analysisPollingId}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        if (data.status === 'complete' || data.status === 'error') {
          setAnalyses(prev => {
            const without = prev.filter(a => a.pathwayId !== data.pathwayId);
            return [...without, data];
          });
          setAnalysisPollingId(null);
          setRunningAnalysis(false);
          clearInterval(interval);
        }
      } catch {}
    }, 3000);
    return () => clearInterval(interval);
  }, [analysisPollingId, token]);

  // Fetch full analysis detail when a complete analysis is selected but missing detail fields
  // (happens when analyses loaded from list endpoint which only returns summary, not strengths/gaps/etc)
  useEffect(() => {
    if (!selectedId || !token) return;
    const a = analyses.find(x => x.pathwayId === selectedId);
    if (!a || a.status !== 'complete' || a.strengths !== undefined) return;
    fetch(`${API_BASE}/api/cdp/gap-analysis/${a.id}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (data?.ok && data.analysis) {
          setAnalyses(prev => {
            const without = prev.filter(x => x.id !== data.analysis.id);
            return [...without, data.analysis];
          });
        }
      })
      .catch(() => {});
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedId, token]);

  const handleGenerate = async () => {
    setGenerating(true);
    setGenerationError(null);
    try {
      const res = await fetch(`${API_BASE}/api/cdp/students/me/pathways/generate`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      });
      const data = await res.json();
      if (!data.ok) throw new Error(data.error || 'Failed to start generation');
      setGenerationJobId(data.job_id);
    } catch (err) {
      setGenerationError(err instanceof Error ? err.message : 'Failed to start generation');
      setGenerating(false);
    }
  };

  const handleRunAnalysis = async (pathwayId: string, force = false) => {
    setRunningAnalysis(true);
    setRunError(null);

    // Optimistic entry
    const selectedPathwayTitle = getPathwayById(pathwayId)?.title || pathwayId;
    setAnalyses(prev => {
      const without = prev.filter(a => a.pathwayId !== pathwayId);
      return [...without, {
        id: 'optimistic-' + pathwayId,
        pathwayId,
        pathwayName: selectedPathwayTitle,
        status: 'queued' as const,
        overallMatch: null, readinessLevel: null, summary: null,
        strengths: [], gaps: [], skillBreakdown: [], recommendations: [],
        radarData: { axes: [], studentScores: [], requiredScores: [] },
        timelineEst: null, autoGenerated: false, error: null,
        createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
      }];
    });

    try {
      const res = await fetch(`${API_BASE}/api/cdp/gap-analysis/run`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ pathway_id: pathwayId, force }),
      });
      const data = await res.json();
      if (!data.ok) throw new Error(data.error || 'Failed to start analysis');

      if (data.status === 'complete' && data.cached) {
        const detailRes = await fetch(`${API_BASE}/api/cdp/gap-analysis/${data.job_id}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const detail = await detailRes.json();
        if (detail.ok) {
          setAnalyses(prev => {
            const without = prev.filter(a => a.pathwayId !== pathwayId);
            return [...without, detail.analysis];
          });
        }
        setRunningAnalysis(false);
      } else {
        setAnalysisPollingId(data.job_id);
      }
    } catch (err) {
      setRunError(err instanceof Error ? err.message : 'Failed to start analysis');
      setRunningAnalysis(false);
      // Remove optimistic entry
      setAnalyses(prev => prev.filter(a => a.id !== 'optimistic-' + pathwayId));
    }
  };

  const handleSave = async (pathwayId: string) => {
    try {
      const res = await fetch(`${API_BASE}/api/cdp/students/me/pathways/save`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ pathway_id: pathwayId }),
      });
      const data = await res.json();
      if (data.ok) {
        await loadAssigned();
        setSelectedId(pathwayId);
      }
    } catch {}
  };

  const handleRemove = async (pathwayId: string) => {
    try {
      const res = await fetch(`${API_BASE}/api/cdp/students/me/pathways/${pathwayId}`, {
        method: 'DELETE',
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.ok) {
        setAssignedPathways(prev => prev.filter(p => p.pathway_id !== pathwayId));
        if (selectedId === pathwayId) setSelectedId(null);
      }
    } catch {}
  };

  const handleDragEnd = async (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over || active.id === over.id) return;
    const oldIdx = assignedPathways.findIndex(p => p.pathway_id === active.id);
    const newIdx = assignedPathways.findIndex(p => p.pathway_id === over.id);
    if (oldIdx < 0 || newIdx < 0) return;
    const newOrder = arrayMove(assignedPathways, oldIdx, newIdx);
    setAssignedPathways(newOrder);
    try {
      await fetch(`${API_BASE}/api/cdp/students/me/pathways/reorder`, {
        method: 'PUT',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ order: newOrder.map(p => p.pathway_id) }),
      });
    } catch {}
  };

  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }));

  // ─── Data helpers ──────────────────────────────────────────────────────────

  function getPathwayById(id: string): PathwayItem | undefined {
    return allPathways.find(p => p.id === id);
  }

  const assignedPathwayIds = new Set(assignedPathways.map(p => p.pathway_id));

  // Build sidebar lists
  const filteredAll = searchQuery.trim()
    ? allPathways.filter(p =>
        p.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        p.career_field?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (Array.isArray(p.keywords) ? p.keywords : []).some((k: string) => k.toLowerCase().includes(searchQuery.toLowerCase()))
      )
    : allPathways;

  const sidebarAssigned = assignedPathways; // order from API is already correct

  const sidebarUnassigned = filteredAll.filter(p => !assignedPathwayIds.has(p.id));

  // Selected pathway data
  const selectedAssigned = assignedPathways.find(p => p.pathway_id === selectedId);
  const selectedItem = selectedId ? getPathwayById(selectedId) : null;
  const selectedAnalysis = selectedId ? analyses.find(a => a.pathwayId === selectedId) || null : null;

  // Derived title and desc for the right pane
  const displayTitle = selectedAssigned?.title || selectedItem?.title || '';
  const displayDesc = selectedAssigned?.description || selectedItem?.description || '';
  const displayField = selectedAssigned?.career_field || selectedItem?.career_field || '';

  const isLoading = loadingPathways || loadingAssigned || loadingAnalyses;

  // ─── Render ────────────────────────────────────────────────────────────────

  return (
    <>
      <Nav />
      <main id="main">
        <div className="page-header">
          <div className="page-container">
            <h1>My Career Pathways</h1>
            <p>Your saved career pathways — explore the full library, save pathways, and run gap analyses</p>
          </div>
        </div>

        <div className="page-container" style={{ padding: 'var(--sp-lg) 1.25rem var(--sp-2xl)' }}>

          {/* Locked state */}
          {isLocked && <LockedState completeness={completeness} />}

          {/* Error states */}
          {generationError && (
            <div style={{ background: 'var(--error-bg)', border: '1px solid rgba(185,28,28,0.2)', borderRadius: 'var(--radius-md)', padding: 'var(--sp-md)', marginBottom: 'var(--sp-lg)', display: 'flex', alignItems: 'center', gap: '0.75rem', flexWrap: 'wrap' }}>
              <p style={{ fontSize: 'var(--text-sm)', color: 'var(--error)', flex: 1 }}>{generationError}</p>
              <button className="btn btn-sm" style={{ background: 'var(--brand-600)', color: '#fff', border: 'none' }} onClick={() => { setGenerationError(null); autoTriggeredRef.current = false; }}>
                Try again
              </button>
            </div>
          )}

          {/* Main two-pane layout */}
          {!isLocked && (
            <div style={{ display: 'grid', gridTemplateColumns: '260px 1fr', gap: 'var(--sp-xl)', alignItems: 'start' }}>

              {/* ── LEFT SIDEBAR ── */}
              <div style={{ position: 'sticky', top: '1rem' }}>
                {/* Search */}
                <div style={{ marginBottom: 'var(--sp-md)' }}>
                  <input
                    type="search"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search pathways…"
                    style={{ width: '100%', padding: '0.5rem 0.75rem', fontSize: 'var(--text-xs)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)', background: 'var(--surface)', color: 'var(--text-default)', outline: 'none', boxSizing: 'border-box' }}
                    onFocus={(e) => { (e.target as HTMLInputElement).style.borderColor = 'var(--brand-400)'; }}
                    onBlur={(e) => { (e.target as HTMLInputElement).style.borderColor = 'var(--border)'; }}
                  />
                </div>

                {/* Just generated toast */}
                {justGenerated && (
                  <div style={{ background: 'rgba(76,175,80,0.08)', border: '1px solid rgba(76,175,80,0.25)', borderRadius: 'var(--radius-md)', padding: 'var(--sp-sm)', marginBottom: 'var(--sp-md)', fontSize: 'var(--text-xs)', color: '#2e7d32', fontWeight: 600 }}>
                    🎉 Your pathways are ready!
                  </div>
                )}

                {/* YOUR PATHWAYS section */}
                {/* Show section when: loading, generating, has pathways, OR auto-gen is about to start (qualified profile, no pathways yet) */}
                {(loadingAssigned || generating || sidebarAssigned.length > 0 || (!isLocked && !loadingAssigned && assignedPathways.length === 0 && !generationError)) && (
                  <div style={{ marginBottom: 'var(--sp-md)' }}>
                    <div style={{ fontSize: '0.65rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: '0.375rem', padding: '0 0.25rem' }}>
                      Your Pathways
                    </div>
                    {loadingAssigned ? (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                        {[1, 2, 3].map(i => <div key={i} style={{ height: 32, borderRadius: 'var(--radius-md)', background: 'var(--surface-2)', animation: 'skeletonPulse 1.5s ease-in-out infinite' }} />)}
                      </div>
                    ) : (generating || (!isLocked && assignedPathways.length === 0 && !generationError)) && sidebarAssigned.length === 0 ? (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.125rem' }}>
                        {[1, 2, 3].map(i => (
                          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 0.625rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)', background: 'var(--surface)', opacity: 0.85 }}>
                            <span style={{ fontSize: '0.6rem', color: 'var(--brand-400)', flexShrink: 0, lineHeight: 1 }}>●</span>
                            <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', fontStyle: 'italic', flex: 1 }}>
                              Researching pathway…
                            </span>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
                        <SortableContext items={sidebarAssigned.map(ap => ap.pathway_id)} strategy={verticalListSortingStrategy}>
                          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.125rem' }}>
                            {sidebarAssigned.map((ap) => {
                              const matchScore = ap.gap_analysis?.status === 'complete' ? ap.gap_analysis?.overall_match : null;
                              return (
                                <SortableSidebarItem
                                  key={ap.pathway_id}
                                  pathwayId={ap.pathway_id}
                                  label={ap.short_name || ap.title}
                                  isSelected={selectedId === ap.pathway_id}
                                  matchScore={matchScore}
                                  fitScore={ap.fit_score}
                                  onClick={() => setSelectedId(ap.pathway_id)}
                                  onRemove={handleRemove}
                                />
                              );
                            })}
                          </div>
                        </SortableContext>
                      </DndContext>
                    )}
                  </div>
                )}

                {/* Divider */}
                {(sidebarAssigned.length > 0 || generating || (!isLocked && !loadingAssigned && assignedPathways.length === 0 && !generationError)) && <div style={{ borderTop: '1px solid var(--border)', marginBottom: 'var(--sp-md)' }} />}

                {/* ALL PATHWAYS section */}
                <div>
                  <div style={{ fontSize: '0.65rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: '0.375rem', padding: '0 0.25rem' }}>
                    All Pathways {!loadingPathways && sidebarUnassigned.length > 0 && <span style={{ fontWeight: 400, color: 'var(--text-faint)' }}>({sidebarUnassigned.length})</span>}
                  </div>
                  {loadingPathways ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                      {[1,2,3,4,5].map(i => <div key={i} style={{ height: 28, borderRadius: 'var(--radius-md)', background: 'var(--surface-2)', animation: 'skeletonPulse 1.5s ease-in-out infinite' }} />)}
                    </div>
                  ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.125rem', maxHeight: 'calc(100vh - 380px)', overflowY: 'auto', paddingRight: '0.125rem' }}>
                      {sidebarUnassigned.map(p => (
                        <SidebarItem
                          key={p.id}
                          pathwayId={p.id}
                          label={p.short_name || p.title}
                          isSelected={selectedId === p.id}
                          isAssigned={false}
                          matchScore={analyses.find(a => a.pathwayId === p.id && a.status === 'complete')?.overallMatch}
                          onClick={() => setSelectedId(p.id)}
                        />
                      ))}
                      {sidebarUnassigned.length === 0 && searchQuery && (
                        <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', padding: '0.375rem 0.625rem', lineHeight: 1.5 }}>No pathways match "{searchQuery}"</p>
                      )}
                    </div>
                  )}
                </div>
              </div>

              {/* ── RIGHT CONTENT ── */}
              <div>
                {!selectedId && !isLoading && (
                  <div style={{ textAlign: 'center', padding: 'var(--sp-2xl)', color: 'var(--text-muted)' }}>
                    <div style={{ fontSize: '2.5rem', marginBottom: 'var(--sp-md)', opacity: 0.3 }}>→</div>
                    <p style={{ fontSize: 'var(--text-sm)' }}>Select a pathway from the sidebar to view details and gap analysis</p>
                  </div>
                )}

                {selectedId && (displayTitle || isLoading) && (
                  <>
                    {/* Pathway header */}
                    <div className="card" style={{ marginBottom: 'var(--sp-md)' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 'var(--sp-md)' }}>
                        <div style={{ flex: 1 }}>
                          {/* Saved pathway badges */}
                          {selectedAssigned && (
                            <div style={{ display: 'flex', gap: '0.375rem', marginBottom: 'var(--sp-sm)', alignItems: 'center', flexWrap: 'wrap' }}>
                              {selectedAssigned.fit_score != null && (
                                <span style={{ fontSize: 'var(--text-xs)', fontWeight: 600, color: 'var(--brand-700)', background: 'var(--brand-50)', borderRadius: 'var(--radius-sm)', padding: '2px 8px' }}>
                                  {selectedAssigned.fit_score}% fit
                                </span>
                              )}
                              {selectedAssigned.gap_analysis?.status === 'complete' && selectedAssigned.gap_analysis?.overall_match != null && (
                                <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: 'var(--white, #fff)', background: matchColor(selectedAssigned.gap_analysis.overall_match), borderRadius: 'var(--radius-sm)', padding: '2px 8px' }}>
                                  {selectedAssigned.gap_analysis.overall_match}% match
                                </span>
                              )}
                              <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', fontStyle: 'italic' }}>
                                Your pathway
                              </span>
                            </div>
                          )}

                          {/* Career field */}
                          {displayField && (
                            <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: 'var(--brand-700)', background: 'var(--brand-50)', borderRadius: 'var(--radius-sm)', padding: '2px 8px', textTransform: 'uppercase', letterSpacing: '0.05em', display: 'inline-block', marginBottom: 'var(--sp-sm)' }}>
                              {displayField}
                            </span>
                          )}

                          <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 800, color: 'var(--text-strong)', fontFamily: 'Plus Jakarta Sans, sans-serif', marginBottom: '0.375rem' }}>
                            {displayTitle}
                          </h2>
                          {displayDesc && (
                            <p style={{ color: 'var(--text-muted)', fontSize: 'var(--text-sm)', lineHeight: 1.6 }}>{displayDesc}</p>
                          )}
                          {selectedAssigned?.notes && (
                            <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', fontStyle: 'italic', marginTop: '0.375rem' }}>{selectedAssigned.notes}</p>
                          )}
                          {selectedAssigned && (
                            <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', marginTop: '0.375rem' }}>
                              {selectedAssigned.mapped_programs_count} internship program{selectedAssigned.mapped_programs_count !== 1 ? 's' : ''} aligned ·{' '}
                              <Link to={`/opportunities?pathway=${selectedId}`} style={{ color: 'var(--brand-700)' }}>Browse opportunities →</Link>
                            </p>
                          )}
                        </div>

                        {/* Analysis button + Remove button for assigned pathways */}
                        {selectedAssigned && (
                          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.375rem', alignItems: 'flex-end', flexShrink: 0 }}>
                            {(!selectedAnalysis || selectedAnalysis.status === 'error') && (
                              <button className="btn btn-primary btn-sm" onClick={() => handleRunAnalysis(selectedId)} disabled={runningAnalysis}>
                                {runningAnalysis ? 'Starting…' : '▶ Run Analysis'}
                              </button>
                            )}
                            {selectedAnalysis?.status === 'complete' && (
                              <button className="btn btn-ghost btn-sm" onClick={() => handleRunAnalysis(selectedId, true)} disabled={runningAnalysis}>
                                ↺ Re-run
                              </button>
                            )}

                          </div>
                        )}
                      </div>
                    </div>

                    {/* Run error */}
                    {runError && (
                      <div style={{ color: 'var(--error, #dc2626)', fontSize: 'var(--text-sm)', padding: '0.5rem 0.75rem', background: 'rgba(220,38,38,0.06)', borderRadius: 'var(--radius-md)', marginBottom: 'var(--sp-md)', border: '1px solid rgba(220,38,38,0.2)' }}>
                        {runError}
                      </div>
                    )}

                    {/* Gap Analysis Panel — if this pathway has analysis */}
                    {selectedAnalysis && (
                      <AnalysisPanel
                        analysis={selectedAnalysis}
                        pathwayTitle={displayTitle}
                        pathwayId={selectedId}
                        onRefresh={(pid) => handleRunAnalysis(pid, true)}
                      />
                    )}

                    {/* Unassigned pathway panel — run analysis or save */}
                    {!selectedAssigned && selectedItem && (
                      <UnassignedPanel
                        pathway={selectedItem}
                        token={token}
                        onRunAnalysis={handleRunAnalysis}
                        onSave={handleSave}
                        hasAnalysis={!!selectedAnalysis}
                        runningAnalysis={runningAnalysis}
                      />
                    )}

                    {/* Assigned pathway but no analysis yet */}
                    {selectedAssigned && !selectedAnalysis && (
                      <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-2xl)', color: 'var(--text-muted)' }}>
                        <div style={{ fontSize: '2rem', marginBottom: 'var(--sp-md)', opacity: 0.4 }}>🧠</div>
                        <p style={{ fontSize: 'var(--text-sm)', marginBottom: 'var(--sp-md)' }}>
                          No gap analysis yet for <strong>{displayTitle}</strong>
                        </p>
                        <button className="btn btn-primary" onClick={() => handleRunAnalysis(selectedId)} disabled={runningAnalysis}>
                          {runningAnalysis ? 'Starting analysis…' : 'Run Gap Analysis'}
                        </button>
                        <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', marginTop: 'var(--sp-sm)' }}>Usually takes 30–60 seconds</p>
                      </div>
                    )}
                  </>
                )}
              </div>
            </div>
          )}
        </div>
      </main>

      <style>{`
        @keyframes skeletonPulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.4; }
        }
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
        @keyframes researchPulse {
          0%, 100% { opacity: 0.4; transform: scale(1); }
          50% { opacity: 1; transform: scale(1.25); }
        }
        @keyframes gapPulse {
          0%, 100% { transform: translateX(-40%); }
          50% { transform: translateX(140%); }
        }
        @media (max-width: 900px) {
          .pathways-layout { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </>
  );
}
