import { useState, useEffect, useCallback, useRef, Fragment } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import Nav from '../components/Nav';
import RadarChart from '../components/RadarChart';
import { getCurrentUser, getStudentData } from '../auth';

const API_BASE = (import.meta.env.VITE_API_URL as string) || 'https://app.lablinkinitiative.org';

// ─── Types ────────────────────────────────────────────────────────────────────

interface PathwayItem {
  id: string;
  title: string;
  short_name: string;
  description: string;
  career_field: string;
  entry_level: string | null;
  keywords: string[];
  usage_count: number;
  requirements?: Record<string, unknown>;
}

interface AssignedPathway {
  id: number;
  pathway_id: string;
  title: string;
  short_name: string;
  description: string;
  career_field: string;
  fit_score: number;
  fit_tier: 'high' | 'medium' | 'stretch';
  notes: string | null;
  is_default: boolean;
  assigned_at: string;
  gap_analysis: { id: string; status: string; overall_match: number | null; summary: string | null } | null;
  mapped_programs_count: number;
}

interface SkillBreakdownItem {
  skill: string;
  studentLevel: number;
  requiredLevel: number;
  gap: number;
  status: 'meets' | 'partial' | 'gap';
  rationale?: string;
}

interface Recommendation {
  priority: 'high' | 'medium' | 'low';
  text: string;
  resource: string | null;
}

interface GapAnalysis {
  id: string;
  pathwayId: string;
  pathwayName: string;
  status: 'queued' | 'processing' | 'complete' | 'error';
  overallMatch: number | null;
  readinessLevel: string | null;
  summary: string | null;
  strengths: string[];
  gaps: string[];
  skillBreakdown: SkillBreakdownItem[];
  recommendations: Recommendation[];
  radarData: { axes: string[]; studentScores: number[]; requiredScores: number[] };
  timelineEst: string | null;
  autoGenerated: boolean;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

// ─── Tier config ──────────────────────────────────────────────────────────────

const TIER_CONFIG = {
  high: { label: 'Almost There', color: '#4caf50', bg: 'rgba(76,175,80,0.08)', border: 'rgba(76,175,80,0.25)', icon: '●' },
  medium: { label: 'Achievable', color: '#ff9800', bg: 'rgba(255,152,0,0.08)', border: 'rgba(255,152,0,0.25)', icon: '◑' },
  stretch: { label: 'Think Big', color: '#2196f3', bg: 'rgba(33,150,243,0.08)', border: 'rgba(33,150,243,0.25)', icon: '○' },
};


// ─── Helpers ──────────────────────────────────────────────────────────────────

function matchColor(pct: number | null) {
  if (pct === null) return 'var(--text-muted)';
  if (pct >= 70) return 'var(--success, #15803d)';
  if (pct >= 45) return 'var(--warning, #b45309)';
  return 'var(--error, #dc2626)';
}

function readinessLabel(level: string | null, pct: number | null): string {
  if (level === 'strong_candidate') return 'Strong candidate';
  if (level === 'ready') return 'Ready to apply';
  if (level === 'building') return 'Building readiness';
  if (level === 'early_stage') return 'Early stage — keep building';
  if (pct !== null) {
    if (pct >= 70) return 'Strong candidate';
    if (pct >= 45) return 'Building readiness';
    return 'Early stage — keep building';
  }
  return '';
}

// ─── Locked State ─────────────────────────────────────────────────────────────

function LockedState({ completeness }: { completeness: number }) {
  const needed = 60 - completeness;
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', padding: 'var(--sp-2xl) var(--sp-lg)' }}>
      <div style={{ width: 72, height: 72, borderRadius: '50%', background: 'var(--surface)', border: '2px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.75rem', marginBottom: 'var(--sp-md)', boxShadow: 'var(--shadow-sm)' }}>
        <span style={{ lineHeight: 1 }}>&#128274;</span>
      </div>
      <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 800, color: 'var(--text-strong)', fontFamily: 'Plus Jakarta Sans, sans-serif', marginBottom: '0.5rem' }}>
        Complete Your Profile to Unlock Pathways
      </h2>
      <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', lineHeight: 1.6, maxWidth: 420, marginBottom: 'var(--sp-lg)' }}>
        {needed > 0
          ? `You're ${completeness}% complete — add ${needed}% more and we'll automatically generate your personalized career pathways.`
          : 'Almost there! Finish your profile and your pathways will generate automatically.'}
      </p>
      <div style={{ width: '100%', maxWidth: 360, marginBottom: 'var(--sp-lg)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.375rem' }}>
          <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', fontWeight: 600 }}>Profile progress</span>
          <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: 'var(--brand-700)' }}>{completeness}% / 60% needed</span>
        </div>
        <div style={{ height: 10, background: 'var(--surface-2)', borderRadius: 99, overflow: 'hidden' }}>
          <div style={{ height: '100%', width: `${Math.min(100, (completeness / 60) * 100)}%`, background: completeness >= 40 ? 'var(--brand-500)' : 'var(--brand-300)', borderRadius: 99, transition: 'width 0.4s ease' }} />
        </div>
      </div>
      <div style={{ display: 'flex', gap: 'var(--sp-sm)', flexWrap: 'wrap', justifyContent: 'center' }}>
        <Link to="/profile" className="btn btn-primary">Update Profile →</Link>
        <Link to="/resume" className="btn btn-secondary">Upload Resume</Link>
      </div>
    </div>
  );
}

// ─── Gap Analysis Panel ───────────────────────────────────────────────────────

interface AnalysisPanelProps {
  analysis: GapAnalysis;
  pathwayTitle: string;
  onRefresh: (pathwayId: string) => void;
  pathwayId: string;
}

function AnalysisPanel({ analysis, pathwayTitle, onRefresh, pathwayId }: AnalysisPanelProps) {
  if (analysis.status === 'queued' || analysis.status === 'processing') {
    return (
      <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-2xl)' }}>
        <div style={{ fontSize: '2rem', marginBottom: 'var(--sp-md)' }}>🧠</div>
        <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-lg)', fontWeight: 700, marginBottom: '0.5rem' }}>Analyzing your profile…</h3>
        <p style={{ color: 'var(--text-muted)', fontSize: 'var(--text-sm)', marginBottom: 'var(--sp-lg)' }}>
          Claude is reading your full profile and reasoning about your readiness for <strong>{pathwayTitle}</strong>. Usually takes 30–60 seconds.
        </p>
        <div style={{ height: 6, background: 'var(--surface-2)', borderRadius: 99, overflow: 'hidden', maxWidth: 300, margin: '0 auto var(--sp-md)' }}>
          <div style={{ height: '100%', width: '60%', background: 'var(--brand-500)', borderRadius: 99, animation: 'gapPulse 2s ease-in-out infinite' }} />
        </div>
        <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)' }}>Status: {analysis.status}</p>
      </div>
    );
  }

  if (analysis.status === 'error') {
    return (
      <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-xl)' }}>
        <div style={{ fontSize: '1.5rem', marginBottom: '0.5rem' }}>⚠️</div>
        <p style={{ color: 'var(--error, #dc2626)', fontWeight: 600, marginBottom: '0.5rem' }}>Analysis failed</p>
        <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', marginBottom: 'var(--sp-md)' }}>{analysis.error}</p>
        <button className="btn btn-primary btn-sm" onClick={() => onRefresh(pathwayId)}>Try Again</button>
      </div>
    );
  }

  return (
    <div>
      {/* Summary */}
      <div className="card" style={{ marginBottom: 'var(--sp-md)', background: 'linear-gradient(135deg, rgba(154,184,46,0.06) 0%, var(--surface) 60%)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: '2.5rem', fontWeight: 800, color: matchColor(analysis.overallMatch), lineHeight: 1 }}>{analysis.overallMatch}%</div>
            <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', marginTop: '0.25rem' }}>Match</div>
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 'var(--text-xs)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: matchColor(analysis.overallMatch), marginBottom: '0.25rem' }}>
              {readinessLabel(analysis.readinessLevel, analysis.overallMatch)}
            </div>
            <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>
              {analysis.timelineEst && `Timeline: ${analysis.timelineEst}`}
              {analysis.autoGenerated && <span style={{ marginLeft: '0.5rem', background: 'var(--surface-2)', borderRadius: 4, padding: '1px 5px' }}>auto</span>}
            </div>
          </div>
        </div>
        <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-default)', lineHeight: 1.65 }}>{analysis.summary}</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.5fr', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
        {analysis.strengths.length > 0 && (
          <div className="card">
            <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--success, #15803d)', marginBottom: 'var(--sp-sm)' }}>✓ Strengths</h3>
            <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.375rem' }}>
              {analysis.strengths.map((s, i) => <li key={i} style={{ fontSize: 'var(--text-xs)', color: 'var(--text-default)', lineHeight: 1.5 }}>{s}</li>)}
            </ul>
          </div>
        )}
        {analysis.gaps.length > 0 && (
          <div className="card">
            <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--error, #dc2626)', marginBottom: 'var(--sp-sm)' }}>↑ Areas to Develop</h3>
            <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.375rem' }}>
              {analysis.gaps.map((g, i) => <li key={i} style={{ fontSize: 'var(--text-xs)', color: 'var(--text-default)', lineHeight: 1.5 }}>{g}</li>)}
            </ul>
          </div>
        )}
      </div>

      {(analysis.radarData?.axes?.length > 2 || analysis.skillBreakdown.length > 0) && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.5fr', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
          {analysis.radarData?.axes?.length > 2 && (
            <div className="card">
              <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--text-muted)', marginBottom: 'var(--sp-sm)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Skills Radar</h3>
              <RadarChart axes={analysis.radarData.axes} studentScores={analysis.radarData.studentScores} requiredScores={analysis.radarData.requiredScores} />
            </div>
          )}
          {analysis.skillBreakdown.length > 0 && (
            <div className="card">
              <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--text-strong)', marginBottom: 'var(--sp-sm)' }}>Skill Breakdown</h3>
              <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr auto auto', gap: '0.4rem 0.75rem', alignItems: 'center', fontSize: '0.7rem' }}>
                {['Skill', 'Level', 'Req', 'Status'].map(h => <div key={h} style={{ fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{h}</div>)}
                {analysis.skillBreakdown.slice(0, 8).map((item, i) => (
                  <Fragment key={i}>
                    <div style={{ color: 'var(--text-default)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 130 }} title={item.skill}>
                      {item.skill.length > 22 ? item.skill.slice(0, 20) + '…' : item.skill}
                    </div>
                    <div style={{ height: 7, background: 'var(--surface-2)', borderRadius: 99, overflow: 'hidden' }}>
                      <div style={{ height: '100%', width: `${Math.round((item.studentLevel || 0) * 100)}%`, background: item.status === 'meets' ? 'var(--success, #15803d)' : item.status === 'partial' ? 'var(--warning, #b45309)' : 'var(--error, #dc2626)', borderRadius: 99 }} />
                    </div>
                    <div style={{ color: 'var(--text-muted)', textAlign: 'center' }}>{Math.round((item.requiredLevel || 0) * 100)}%</div>
                    <div style={{ fontSize: '0.6rem', fontWeight: 700, textTransform: 'capitalize', color: item.status === 'meets' ? 'var(--success, #15803d)' : item.status === 'partial' ? 'var(--warning, #b45309)' : 'var(--error, #dc2626)' }}>
                      {item.status}
                    </div>
                  </Fragment>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {analysis.recommendations.length > 0 && (
        <div className="card" style={{ marginBottom: 'var(--sp-md)' }}>
          <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--text-strong)', marginBottom: 'var(--sp-md)' }}>Recommendations</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-sm)' }}>
            {analysis.recommendations.map((rec, i) => (
              <div key={i} style={{ display: 'flex', gap: '0.75rem', padding: 'var(--sp-sm)', background: rec.priority === 'high' ? 'rgba(220,38,38,0.05)' : rec.priority === 'medium' ? 'rgba(251,191,36,0.08)' : 'var(--surface)', borderRadius: 'var(--radius-md)', border: `1px solid ${rec.priority === 'high' ? 'rgba(185,28,28,0.12)' : rec.priority === 'medium' ? 'rgba(180,83,9,0.12)' : 'var(--border)'}` }}>
                <div style={{ width: 20, height: 20, borderRadius: '50%', flexShrink: 0, background: rec.priority === 'high' ? 'var(--error, #dc2626)' : rec.priority === 'medium' ? 'var(--warning, #b45309)' : 'var(--text-faint)', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.55rem', fontWeight: 800, textTransform: 'uppercase', marginTop: '0.125rem' }}>
                  {rec.priority[0].toUpperCase()}
                </div>
                <div>
                  <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-default)', lineHeight: 1.55 }}>{rec.text}</p>
                  {rec.resource && <a href={rec.resource} target="_blank" rel="noopener noreferrer" style={{ fontSize: 'var(--text-xs)', color: 'var(--brand-700)', textDecoration: 'underline', marginTop: '0.25rem', display: 'inline-block' }}>Learn more ↗</a>}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div style={{ marginTop: 'var(--sp-sm)', display: 'flex', gap: 'var(--sp-sm)', alignItems: 'center', flexWrap: 'wrap' }}>
        <button onClick={() => onRefresh(pathwayId)} className="btn btn-ghost btn-sm">↺ Re-run analysis</button>
        <Link to="/profile" className="btn btn-ghost btn-sm">Update skills →</Link>
        <Link to="/opportunities" className="btn btn-ghost btn-sm">Browse programs →</Link>
        <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)' }}>
          {analysis.updatedAt ? `Last run: ${new Date(analysis.updatedAt).toLocaleDateString()}` : ''}
        </span>
      </div>
    </div>
  );
}

// ─── Sidebar Item ─────────────────────────────────────────────────────────────

interface SidebarItemProps {
  pathwayId: string;
  label: string;
  isSelected: boolean;
  isAssigned: boolean;
  assignedTier?: 'high' | 'medium' | 'stretch';
  matchScore?: number | null;
  fitScore?: number;
  onClick: () => void;
}

function SidebarItem({ pathwayId: _pathwayId, label, isSelected, isAssigned, assignedTier, matchScore, fitScore, onClick }: SidebarItemProps) {
  const tier = assignedTier ? TIER_CONFIG[assignedTier] : null;

  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        width: '100%',
        textAlign: 'left',
        padding: '0.5rem 0.625rem',
        borderRadius: 'var(--radius-md)',
        border: isSelected ? `1px solid ${tier?.color || 'var(--brand-500)'}` : '1px solid transparent',
        background: isSelected ? (tier ? tier.bg : 'rgba(154,184,46,0.08)') : 'transparent',
        cursor: 'pointer',
        transition: 'background 0.12s, border-color 0.12s',
        opacity: isAssigned ? 1 : 0.55,
      }}
      onMouseEnter={(e) => { if (!isSelected) (e.currentTarget as HTMLButtonElement).style.background = 'var(--surface)'; }}
      onMouseLeave={(e) => { if (!isSelected) (e.currentTarget as HTMLButtonElement).style.background = 'transparent'; }}
    >
      {/* Tier dot or generic dot */}
      <span style={{ fontSize: '0.6rem', color: tier?.color || 'var(--text-faint)', flexShrink: 0, lineHeight: 1 }}>
        {tier ? tier.icon : '○'}
      </span>

      {/* Title */}
      <span style={{
        fontSize: 'var(--text-xs)',
        fontWeight: isSelected ? 700 : isAssigned ? 600 : 400,
        color: isSelected ? (tier?.color || 'var(--brand-700)') : isAssigned ? 'var(--text-strong)' : 'var(--text-muted)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        flex: 1,
      }}>
        {label}
      </span>

      {/* Match or fit score badge */}
      {isAssigned && (
        <span style={{
          fontSize: '0.65rem',
          fontWeight: 700,
          color: matchScore != null ? matchColor(matchScore) : (tier?.color || 'var(--text-muted)'),
          flexShrink: 0,
          marginLeft: '0.25rem',
        }}>
          {matchScore != null ? `${matchScore}%` : fitScore != null ? `${fitScore}%` : ''}
        </span>
      )}
    </button>
  );
}

// ─── Right Panel: Unassigned Pathway ─────────────────────────────────────────

interface UnassignedPanelProps {
  pathway: PathwayItem;
  assignedPathways: AssignedPathway[];
  token: string | null;
  onRunAnalysis: (pathwayId: string) => void;
  onSwapped: (tier: string, pathwayId: string, title: string) => void;
  hasAnalysis: boolean;
  runningAnalysis: boolean;
}

function UnassignedPanel({ pathway, assignedPathways, token, onRunAnalysis, onSwapped, hasAnalysis, runningAnalysis }: UnassignedPanelProps) {
  const [swapping, setSwapping] = useState(false);
  const [showSwapMenu, setShowSwapMenu] = useState(false);
  const [swapMsg, setSwapMsg] = useState<string | null>(null);
  const hasAssignments = assignedPathways.length > 0;

  const handleSwap = async (tier: string) => {
    setSwapping(true);
    setShowSwapMenu(false);
    try {
      const res = await fetch(`${API_BASE}/api/cdp/students/me/pathways/swap`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ tier, pathway_id: pathway.id }),
      });
      const data = await res.json();
      if (data.ok) {
        setSwapMsg(`Swapped into "${TIER_CONFIG[tier as keyof typeof TIER_CONFIG]?.label || tier}" slot`);
        onSwapped(tier, pathway.id, pathway.title);
        setTimeout(() => setSwapMsg(null), 3000);
      } else {
        setSwapMsg(`Error: ${data.error || 'Failed to swap'}`);
        setTimeout(() => setSwapMsg(null), 4000);
      }
    } catch {
      setSwapMsg('Network error — try again');
      setTimeout(() => setSwapMsg(null), 4000);
    }
    setSwapping(false);
  };

  const keywords = Array.isArray(pathway.keywords) ? pathway.keywords : (typeof pathway.keywords === 'string' ? (pathway.keywords as string).split(',').map((k: string) => k.trim()) : []);

  return (
    <div>
      <div className="card" style={{ marginBottom: 'var(--sp-md)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.375rem', marginBottom: 'var(--sp-sm)' }}>
              <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: 'var(--brand-700)', background: 'var(--brand-50)', borderRadius: 'var(--radius-sm)', padding: '2px 8px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                {pathway.career_field}
              </span>
              {pathway.entry_level && (
                <span style={{ fontSize: 'var(--text-xs)', fontWeight: 600, color: 'var(--text-muted)', background: 'var(--surface-2)', borderRadius: 'var(--radius-sm)', padding: '2px 6px' }}>
                  {pathway.entry_level}
                </span>
              )}
            </div>
            <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', lineHeight: 1.6 }}>{pathway.description}</p>
            {keywords.length > 0 && (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.25rem', marginTop: 'var(--sp-sm)' }}>
                {keywords.slice(0, 6).map((kw: string) => (
                  <span key={kw} style={{ fontSize: '0.7rem', color: 'var(--text-faint)', background: 'var(--surface-2)', borderRadius: 'var(--radius-sm)', padding: '2px 6px' }}>{kw}</span>
                ))}
              </div>
            )}
          </div>
        </div>

        <div style={{ display: 'flex', gap: 'var(--sp-sm)', flexWrap: 'wrap', alignItems: 'center' }}>
          <button
            className="btn btn-primary btn-sm"
            onClick={() => onRunAnalysis(pathway.id)}
            disabled={runningAnalysis}
          >
            {runningAnalysis ? 'Starting…' : hasAnalysis ? 'Re-run Analysis' : '▶ Run Gap Analysis'}
          </button>

          {hasAssignments && (
            <div style={{ position: 'relative' }}>
              <button
                type="button"
                disabled={swapping}
                onClick={() => setShowSwapMenu(v => !v)}
                style={{ fontSize: 'var(--text-xs)', fontWeight: 600, padding: '5px 10px', borderRadius: 'var(--radius-sm)', border: '1px solid var(--brand-300)', background: 'var(--brand-50)', color: 'var(--brand-700)', cursor: 'pointer', whiteSpace: 'nowrap' }}
              >
                {swapping ? 'Swapping…' : '⇄ Swap into My Pathways'}
              </button>

              {showSwapMenu && (
                <div style={{ position: 'absolute', top: '110%', left: 0, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-md)', padding: '0.375rem', zIndex: 100, minWidth: 200 }}>
                  <p style={{ fontSize: '0.65rem', color: 'var(--text-faint)', padding: '0 4px 4px', fontWeight: 600 }}>REPLACE WHICH SLOT?</p>
                  {(['high', 'medium', 'stretch'] as const).map(tier => {
                    const current = assignedPathways.find(p => p.fit_tier === tier);
                    return (
                      <button key={tier} type="button" onClick={() => handleSwap(tier)} style={{ display: 'block', width: '100%', textAlign: 'left', padding: '5px 8px', borderRadius: 'var(--radius-sm)', border: 'none', background: 'transparent', cursor: 'pointer', fontSize: 'var(--text-xs)', color: 'var(--text-strong)' }}
                        onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'var(--surface-2)'; }}
                        onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'transparent'; }}
                      >
                        <strong>{TIER_CONFIG[tier].label}</strong>
                        {current && <span style={{ color: 'var(--text-faint)', display: 'block', fontSize: '0.65rem' }}>Currently: {current.title.length > 30 ? current.title.slice(0, 28) + '…' : current.title}</span>}
                      </button>
                    );
                  })}
                </div>
              )}
            </div>
          )}
        </div>

        {swapMsg && (
          <div style={{ marginTop: 'var(--sp-sm)', fontSize: 'var(--text-xs)', padding: '4px 8px', borderRadius: 'var(--radius-sm)', background: swapMsg.startsWith('Error') ? 'var(--error-bg)' : 'rgba(76,175,80,0.08)', color: swapMsg.startsWith('Error') ? 'var(--error)' : '#2e7d32', fontWeight: 600 }}>
            {swapMsg}
          </div>
        )}
      </div>

      {!hasAnalysis && (
        <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-xl)', color: 'var(--text-muted)' }}>
          <div style={{ fontSize: '2rem', marginBottom: 'var(--sp-md)', opacity: 0.4 }}>🧠</div>
          <p style={{ fontSize: 'var(--text-sm)', marginBottom: 'var(--sp-md)' }}>No analysis yet for this pathway.</p>
          <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)' }}>Run a gap analysis to see how ready you are and get personalized recommendations.</p>
        </div>
      )}
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function PathwayDashboard() {
  const user = getCurrentUser()!;
  useNavigate();
  const [searchParams] = useSearchParams();
  const token = localStorage.getItem('cdp_token');

  const student = getStudentData(user.uid);
  const completeness = student?.profileCompleteness || 0;
  const isLocked = completeness < 60;

  // Data state
  const [allPathways, setAllPathways] = useState<PathwayItem[]>([]);
  const [assignedPathways, setAssignedPathways] = useState<AssignedPathway[]>([]);
  const [analyses, setAnalyses] = useState<GapAnalysis[]>([]);

  // Loading state
  const [loadingPathways, setLoadingPathways] = useState(true);
  const [loadingAssigned, setLoadingAssigned] = useState(true);
  const [loadingAnalyses, setLoadingAnalyses] = useState(true);

  // Generation state (initial 3 pathways)
  const [generating, setGenerating] = useState(false);
  const [generationJobId, setGenerationJobId] = useState<string | null>(null);
  const [generationError, setGenerationError] = useState<string | null>(null);
  const [justGenerated, setJustGenerated] = useState(false);
  const autoTriggeredRef = useRef(false);

  // Analysis state
  const [runningAnalysis, setRunningAnalysis] = useState(false);
  const [analysisPollingId, setAnalysisPollingId] = useState<string | null>(null);
  const [runError, setRunError] = useState<string | null>(null);

  // UI state
  const [selectedId, setSelectedId] = useState<string | null>(searchParams.get('selected'));
  const [searchQuery, setSearchQuery] = useState('');

  // Redirect from old /pathway/:id route
  useEffect(() => {
    const fromId = searchParams.get('selected');
    if (fromId) setSelectedId(fromId);
  }, [searchParams]);

  // Load all pathways
  useEffect(() => {
    if (isLocked) { setLoadingPathways(false); return; }
    fetch(`${API_BASE}/api/cdp/pathways?limit=100`, {
      headers: { Authorization: `Bearer ${token}` },
    }).then(r => r.json()).then(d => {
      if (d.ok) setAllPathways(d.pathways || []);
    }).catch(() => {}).finally(() => setLoadingPathways(false));
  }, [token, isLocked]);

  // Load assigned pathways
  const loadAssigned = useCallback(async () => {
    if (isLocked) { setLoadingAssigned(false); return; }
    try {
      const res = await fetch(`${API_BASE}/api/cdp/students/me/pathways`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.ok) setAssignedPathways(data.pathways || []);
    } catch {}
    setLoadingAssigned(false);
  }, [token, isLocked]);

  useEffect(() => { loadAssigned(); }, [loadAssigned]);

  // Load gap analyses
  const loadAnalyses = useCallback(async () => {
    if (isLocked) { setLoadingAnalyses(false); return; }
    try {
      const res = await fetch(`${API_BASE}/api/cdp/gap-analyses`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.ok) setAnalyses(data.analyses || []);
    } catch {}
    setLoadingAnalyses(false);
  }, [token, isLocked]);

  useEffect(() => { loadAnalyses(); }, [loadAnalyses]);

  // Auto-select first assigned pathway when data loads
  useEffect(() => {
    if (!selectedId && assignedPathways.length > 0 && !loadingAssigned) {
      setSelectedId(assignedPathways[0].pathway_id);
    }
  }, [assignedPathways, loadingAssigned, selectedId]);

  // Auto-trigger initial generation if profile >= 60% and no pathways
  useEffect(() => {
    if (!loadingAssigned && !isLocked && assignedPathways.length === 0 && !generating && !generationError && !autoTriggeredRef.current) {
      autoTriggeredRef.current = true;
      handleGenerate();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loadingAssigned, isLocked, assignedPathways.length, generating, generationError]);

  // Poll generation job
  useEffect(() => {
    if (!generationJobId) return;
    const interval = setInterval(async () => {
      try {
        const res = await fetch(`${API_BASE}/api/cdp/students/me/pathways/status/${generationJobId}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        if (data.status === 'complete') {
          await loadAssigned();
          await loadAnalyses();
          setGenerating(false);
          setGenerationJobId(null);
          setJustGenerated(true);
          clearInterval(interval);
        } else if (data.status === 'error') {
          setGenerationError(data.error || 'Pathway generation failed. Please try again.');
          setGenerating(false);
          setGenerationJobId(null);
          clearInterval(interval);
        }
      } catch {}
    }, 3000);
    return () => clearInterval(interval);
  }, [generationJobId, token, loadAssigned, loadAnalyses]);

  // Poll gap analysis
  useEffect(() => {
    if (!analysisPollingId) return;
    const interval = setInterval(async () => {
      try {
        const res = await fetch(`${API_BASE}/api/cdp/gap-analysis/status/${analysisPollingId}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        if (data.status === 'complete' || data.status === 'error') {
          setAnalyses(prev => {
            const without = prev.filter(a => a.pathwayId !== data.pathwayId);
            return [...without, data];
          });
          setAnalysisPollingId(null);
          setRunningAnalysis(false);
          clearInterval(interval);
        }
      } catch {}
    }, 3000);
    return () => clearInterval(interval);
  }, [analysisPollingId, token]);

  const handleGenerate = async () => {
    setGenerating(true);
    setGenerationError(null);
    try {
      const res = await fetch(`${API_BASE}/api/cdp/students/me/pathways/generate`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      });
      const data = await res.json();
      if (!data.ok) throw new Error(data.error || 'Failed to start generation');
      setGenerationJobId(data.job_id);
    } catch (err) {
      setGenerationError(err instanceof Error ? err.message : 'Failed to start generation');
      setGenerating(false);
    }
  };

  const handleRunAnalysis = async (pathwayId: string, force = false) => {
    setRunningAnalysis(true);
    setRunError(null);

    // Optimistic entry
    const selectedPathwayTitle = getPathwayById(pathwayId)?.title || pathwayId;
    setAnalyses(prev => {
      const without = prev.filter(a => a.pathwayId !== pathwayId);
      return [...without, {
        id: 'optimistic-' + pathwayId,
        pathwayId,
        pathwayName: selectedPathwayTitle,
        status: 'queued' as const,
        overallMatch: null, readinessLevel: null, summary: null,
        strengths: [], gaps: [], skillBreakdown: [], recommendations: [],
        radarData: { axes: [], studentScores: [], requiredScores: [] },
        timelineEst: null, autoGenerated: false, error: null,
        createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
      }];
    });

    try {
      const res = await fetch(`${API_BASE}/api/cdp/gap-analysis/run`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ pathway_id: pathwayId, force }),
      });
      const data = await res.json();
      if (!data.ok) throw new Error(data.error || 'Failed to start analysis');

      if (data.status === 'complete' && data.cached) {
        const detailRes = await fetch(`${API_BASE}/api/cdp/gap-analysis/${data.job_id}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const detail = await detailRes.json();
        if (detail.ok) {
          setAnalyses(prev => {
            const without = prev.filter(a => a.pathwayId !== pathwayId);
            return [...without, detail.analysis];
          });
        }
        setRunningAnalysis(false);
      } else {
        setAnalysisPollingId(data.job_id);
      }
    } catch (err) {
      setRunError(err instanceof Error ? err.message : 'Failed to start analysis');
      setRunningAnalysis(false);
      // Remove optimistic entry
      setAnalyses(prev => prev.filter(a => a.id !== 'optimistic-' + pathwayId));
    }
  };

  const handleSwapped = (tier: string, pathwayId: string, title: string) => {
    setAssignedPathways(prev => prev.map(p =>
      p.fit_tier === tier ? { ...p, pathway_id: pathwayId, title } : p
    ));
    setSelectedId(pathwayId);
    loadAssigned();
  };

  // ─── Data helpers ──────────────────────────────────────────────────────────

  function getPathwayById(id: string): PathwayItem | undefined {
    return allPathways.find(p => p.id === id);
  }

  const assignedPathwayIds = new Set(assignedPathways.map(p => p.pathway_id));

  // Build sidebar lists
  const filteredAll = searchQuery.trim()
    ? allPathways.filter(p =>
        p.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        p.career_field?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (Array.isArray(p.keywords) ? p.keywords : []).some((k: string) => k.toLowerCase().includes(searchQuery.toLowerCase()))
      )
    : allPathways;

  const sidebarAssigned = assignedPathways.slice().sort((a, b) => {
    const tierOrder = { high: 0, medium: 1, stretch: 2 };
    return (tierOrder[a.fit_tier] ?? 3) - (tierOrder[b.fit_tier] ?? 3);
  });

  const sidebarUnassigned = filteredAll.filter(p => !assignedPathwayIds.has(p.id));

  // Selected pathway data
  const selectedAssigned = assignedPathways.find(p => p.pathway_id === selectedId);
  const selectedItem = selectedId ? getPathwayById(selectedId) : null;
  const selectedAnalysis = selectedId ? analyses.find(a => a.pathwayId === selectedId) || null : null;

  // Derived title and desc for the right pane
  const displayTitle = selectedAssigned?.title || selectedItem?.title || '';
  const displayDesc = selectedAssigned?.description || selectedItem?.description || '';
  const displayField = selectedAssigned?.career_field || selectedItem?.career_field || '';

  const isLoading = loadingPathways || loadingAssigned || loadingAnalyses;

  // ─── Render ────────────────────────────────────────────────────────────────

  return (
    <>
      <Nav />
      <main id="main">
        <div className="page-header">
          <div className="page-container">
            <h1>My Career Pathways</h1>
            <p>Your three personalized pathways — explore the full library and run gap analyses</p>
          </div>
        </div>

        <div className="page-container" style={{ padding: 'var(--sp-lg) 1.25rem var(--sp-2xl)' }}>

          {/* Locked state */}
          {isLocked && <LockedState completeness={completeness} />}

          {/* Error states */}
          {generationError && (
            <div style={{ background: 'var(--error-bg)', border: '1px solid rgba(185,28,28,0.2)', borderRadius: 'var(--radius-md)', padding: 'var(--sp-md)', marginBottom: 'var(--sp-lg)', display: 'flex', alignItems: 'center', gap: '0.75rem', flexWrap: 'wrap' }}>
              <p style={{ fontSize: 'var(--text-sm)', color: 'var(--error)', flex: 1 }}>{generationError}</p>
              <button className="btn btn-sm" style={{ background: 'var(--brand-600)', color: '#fff', border: 'none' }} onClick={() => { setGenerationError(null); autoTriggeredRef.current = false; }}>
                Try again
              </button>
            </div>
          )}

          {/* Main two-pane layout */}
          {!isLocked && (
            <div style={{ display: 'grid', gridTemplateColumns: '260px 1fr', gap: 'var(--sp-xl)', alignItems: 'start' }}>

              {/* ── LEFT SIDEBAR ── */}
              <div style={{ position: 'sticky', top: '1rem' }}>
                {/* Search */}
                <div style={{ marginBottom: 'var(--sp-md)' }}>
                  <input
                    type="search"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search pathways…"
                    style={{ width: '100%', padding: '0.5rem 0.75rem', fontSize: 'var(--text-xs)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)', background: 'var(--surface)', color: 'var(--text-default)', outline: 'none', boxSizing: 'border-box' }}
                    onFocus={(e) => { (e.target as HTMLInputElement).style.borderColor = 'var(--brand-400)'; }}
                    onBlur={(e) => { (e.target as HTMLInputElement).style.borderColor = 'var(--border)'; }}
                  />
                </div>

                {/* Just generated toast */}
                {justGenerated && (
                  <div style={{ background: 'rgba(76,175,80,0.08)', border: '1px solid rgba(76,175,80,0.25)', borderRadius: 'var(--radius-md)', padding: 'var(--sp-sm)', marginBottom: 'var(--sp-md)', fontSize: 'var(--text-xs)', color: '#2e7d32', fontWeight: 600 }}>
                    🎉 Your pathways are ready!
                  </div>
                )}

                {/* YOUR PATHWAYS section */}
                {/* Show section when: loading, generating, has pathways, OR auto-gen is about to start (qualified profile, no pathways yet) */}
                {(loadingAssigned || generating || sidebarAssigned.length > 0 || (!isLocked && !loadingAssigned && assignedPathways.length === 0 && !generationError)) && (
                  <div style={{ marginBottom: 'var(--sp-md)' }}>
                    <div style={{ fontSize: '0.65rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: '0.375rem', padding: '0 0.25rem' }}>
                      Your Pathways
                    </div>
                    {loadingAssigned ? (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                        {[1, 2, 3].map(i => <div key={i} style={{ height: 32, borderRadius: 'var(--radius-md)', background: 'var(--surface-2)', animation: 'skeletonPulse 1.5s ease-in-out infinite' }} />)}
                      </div>
                    ) : (generating || (!isLocked && assignedPathways.length === 0 && !generationError)) && sidebarAssigned.length === 0 ? (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.125rem' }}>
                        {(['high', 'medium', 'stretch'] as const).map(tier => {
                          const tc = TIER_CONFIG[tier];
                          return (
                            <div key={tier} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 0.625rem', borderRadius: 'var(--radius-md)', border: `1px solid ${tc.border}`, background: tc.bg, opacity: 0.85 }}>
                              <span style={{ fontSize: '0.6rem', color: tc.color, flexShrink: 0, lineHeight: 1 }}>{tc.icon}</span>
                              <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', fontStyle: 'italic', flex: 1 }}>
                                Researching pathway…
                              </span>
                              <span style={{ fontSize: '0.6rem', fontWeight: 700, color: tc.color, flexShrink: 0 }}>{tc.label}</span>
                            </div>
                          );
                        })}
                      </div>
                    ) : (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.125rem' }}>
                        {sidebarAssigned.map(ap => {
                          const matchScore = ap.gap_analysis?.status === 'complete' ? ap.gap_analysis?.overall_match : null;
                          return (
                            <SidebarItem
                              key={ap.id}
                              pathwayId={ap.pathway_id}
                              label={ap.short_name || ap.title}
                              isSelected={selectedId === ap.pathway_id}
                              isAssigned={true}
                              assignedTier={ap.fit_tier}
                              matchScore={matchScore}
                              fitScore={ap.fit_score}
                              onClick={() => setSelectedId(ap.pathway_id)}
                            />
                          );
                        })}
                      </div>
                    )}
                  </div>
                )}

                {/* Divider */}
                {(sidebarAssigned.length > 0 || generating || (!isLocked && !loadingAssigned && assignedPathways.length === 0 && !generationError)) && <div style={{ borderTop: '1px solid var(--border)', marginBottom: 'var(--sp-md)' }} />}

                {/* ALL PATHWAYS section */}
                <div>
                  <div style={{ fontSize: '0.65rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: '0.375rem', padding: '0 0.25rem' }}>
                    All Pathways {!loadingPathways && sidebarUnassigned.length > 0 && <span style={{ fontWeight: 400, color: 'var(--text-faint)' }}>({sidebarUnassigned.length})</span>}
                  </div>
                  {loadingPathways ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                      {[1,2,3,4,5].map(i => <div key={i} style={{ height: 28, borderRadius: 'var(--radius-md)', background: 'var(--surface-2)', animation: 'skeletonPulse 1.5s ease-in-out infinite' }} />)}
                    </div>
                  ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.125rem', maxHeight: 'calc(100vh - 380px)', overflowY: 'auto', paddingRight: '0.125rem' }}>
                      {sidebarUnassigned.map(p => (
                        <SidebarItem
                          key={p.id}
                          pathwayId={p.id}
                          label={p.short_name || p.title}
                          isSelected={selectedId === p.id}
                          isAssigned={false}
                          matchScore={analyses.find(a => a.pathwayId === p.id && a.status === 'complete')?.overallMatch}
                          onClick={() => setSelectedId(p.id)}
                        />
                      ))}
                      {sidebarUnassigned.length === 0 && searchQuery && (
                        <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', padding: '0.375rem 0.625rem', lineHeight: 1.5 }}>No pathways match "{searchQuery}"</p>
                      )}
                    </div>
                  )}
                </div>
              </div>

              {/* ── RIGHT CONTENT ── */}
              <div>
                {!selectedId && !isLoading && (
                  <div style={{ textAlign: 'center', padding: 'var(--sp-2xl)', color: 'var(--text-muted)' }}>
                    <div style={{ fontSize: '2.5rem', marginBottom: 'var(--sp-md)', opacity: 0.3 }}>→</div>
                    <p style={{ fontSize: 'var(--text-sm)' }}>Select a pathway from the sidebar to view details and gap analysis</p>
                  </div>
                )}

                {selectedId && (displayTitle || isLoading) && (
                  <>
                    {/* Pathway header */}
                    <div className="card" style={{ marginBottom: 'var(--sp-md)' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 'var(--sp-md)' }}>
                        <div style={{ flex: 1 }}>
                          {/* Tier badge if assigned */}
                          {selectedAssigned && (
                            <div style={{ display: 'flex', gap: '0.375rem', marginBottom: 'var(--sp-sm)', alignItems: 'center', flexWrap: 'wrap' }}>
                              <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: TIER_CONFIG[selectedAssigned.fit_tier].color, background: TIER_CONFIG[selectedAssigned.fit_tier].bg, border: `1px solid ${TIER_CONFIG[selectedAssigned.fit_tier].border}`, borderRadius: 'var(--radius-sm)', padding: '2px 8px', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                                {TIER_CONFIG[selectedAssigned.fit_tier].icon} {TIER_CONFIG[selectedAssigned.fit_tier].label}
                              </span>
                              <span style={{ fontSize: 'var(--text-xs)', fontWeight: 600, color: 'var(--brand-700)', background: 'var(--brand-50)', borderRadius: 'var(--radius-sm)', padding: '2px 8px' }}>
                                {selectedAssigned.fit_score}% fit
                              </span>
                              {selectedAssigned.gap_analysis?.status === 'complete' && selectedAssigned.gap_analysis?.overall_match != null && (
                                <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: 'var(--white, #fff)', background: matchColor(selectedAssigned.gap_analysis.overall_match), borderRadius: 'var(--radius-sm)', padding: '2px 8px' }}>
                                  {selectedAssigned.gap_analysis.overall_match}% match
                                </span>
                              )}
                              <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', fontStyle: 'italic' }}>
                                Your pathway
                              </span>
                            </div>
                          )}

                          {/* Career field */}
                          {displayField && (
                            <span style={{ fontSize: 'var(--text-xs)', fontWeight: 700, color: 'var(--brand-700)', background: 'var(--brand-50)', borderRadius: 'var(--radius-sm)', padding: '2px 8px', textTransform: 'uppercase', letterSpacing: '0.05em', display: 'inline-block', marginBottom: 'var(--sp-sm)' }}>
                              {displayField}
                            </span>
                          )}

                          <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 800, color: 'var(--text-strong)', fontFamily: 'Plus Jakarta Sans, sans-serif', marginBottom: '0.375rem' }}>
                            {displayTitle}
                          </h2>
                          {displayDesc && (
                            <p style={{ color: 'var(--text-muted)', fontSize: 'var(--text-sm)', lineHeight: 1.6 }}>{displayDesc}</p>
                          )}
                          {selectedAssigned?.notes && (
                            <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', fontStyle: 'italic', marginTop: '0.375rem' }}>{selectedAssigned.notes}</p>
                          )}
                          {selectedAssigned && (
                            <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', marginTop: '0.375rem' }}>
                              {selectedAssigned.mapped_programs_count} internship program{selectedAssigned.mapped_programs_count !== 1 ? 's' : ''} aligned ·{' '}
                              <Link to="/opportunities" style={{ color: 'var(--brand-700)' }}>Browse opportunities →</Link>
                            </p>
                          )}
                        </div>

                        {/* Re-run or Run Analysis button in header */}
                        {selectedAssigned && (
                          <>
                            {(!selectedAnalysis || selectedAnalysis.status === 'error') && (
                              <button className="btn btn-primary btn-sm" onClick={() => handleRunAnalysis(selectedId)} disabled={runningAnalysis} style={{ flexShrink: 0 }}>
                                {runningAnalysis ? 'Starting…' : '▶ Run Analysis'}
                              </button>
                            )}
                            {selectedAnalysis?.status === 'complete' && (
                              <button className="btn btn-ghost btn-sm" onClick={() => handleRunAnalysis(selectedId, true)} disabled={runningAnalysis} style={{ flexShrink: 0 }}>
                                ↺ Re-run
                              </button>
                            )}
                          </>
                        )}
                      </div>
                    </div>

                    {/* Run error */}
                    {runError && (
                      <div style={{ color: 'var(--error, #dc2626)', fontSize: 'var(--text-sm)', padding: '0.5rem 0.75rem', background: 'rgba(220,38,38,0.06)', borderRadius: 'var(--radius-md)', marginBottom: 'var(--sp-md)', border: '1px solid rgba(220,38,38,0.2)' }}>
                        {runError}
                      </div>
                    )}

                    {/* Gap Analysis Panel — if this pathway has analysis */}
                    {selectedAnalysis && (
                      <AnalysisPanel
                        analysis={selectedAnalysis}
                        pathwayTitle={displayTitle}
                        pathwayId={selectedId}
                        onRefresh={(pid) => handleRunAnalysis(pid, true)}
                      />
                    )}

                    {/* Unassigned pathway panel — run analysis or swap */}
                    {!selectedAssigned && selectedItem && (
                      <UnassignedPanel
                        pathway={selectedItem}
                        assignedPathways={assignedPathways}
                        token={token}
                        onRunAnalysis={handleRunAnalysis}
                        onSwapped={handleSwapped}
                        hasAnalysis={!!selectedAnalysis}
                        runningAnalysis={runningAnalysis}
                      />
                    )}

                    {/* Assigned pathway but no analysis yet */}
                    {selectedAssigned && !selectedAnalysis && (
                      <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-2xl)', color: 'var(--text-muted)' }}>
                        <div style={{ fontSize: '2rem', marginBottom: 'var(--sp-md)', opacity: 0.4 }}>🧠</div>
                        <p style={{ fontSize: 'var(--text-sm)', marginBottom: 'var(--sp-md)' }}>
                          No gap analysis yet for <strong>{displayTitle}</strong>
                        </p>
                        <button className="btn btn-primary" onClick={() => handleRunAnalysis(selectedId)} disabled={runningAnalysis}>
                          {runningAnalysis ? 'Starting analysis…' : 'Run Gap Analysis'}
                        </button>
                        <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', marginTop: 'var(--sp-sm)' }}>Usually takes 30–60 seconds</p>
                      </div>
                    )}
                  </>
                )}
              </div>
            </div>
          )}
        </div>
      </main>

      <style>{`
        @keyframes skeletonPulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.4; }
        }
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
        @keyframes researchPulse {
          0%, 100% { opacity: 0.4; transform: scale(1); }
          50% { opacity: 1; transform: scale(1.25); }
        }
        @keyframes gapPulse {
          0%, 100% { transform: translateX(-40%); }
          50% { transform: translateX(140%); }
        }
        @media (max-width: 900px) {
          .pathways-layout { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </>
  );
}
