import { useState, useEffect, Fragment, useCallback } from 'react';
import { useParams, Link } from 'react-router-dom';
import Nav from '../components/Nav';
import RadarChart from '../components/RadarChart';
import { getCurrentUser } from '../auth';
import type { Pathway, Program } from '../types';
import pathwaysData from '../data/pathways.json';
import programsData from '../data/programs.json';

const API_BASE = (import.meta.env.VITE_API_URL as string) || 'https://app.lablinkinitiative.org';

const pathways = pathwaysData.pathways as unknown as Pathway[];
const programs = programsData.programs as unknown as Program[];

// ─── Types ─────────────────────────────────────────────────────────────────────

interface SkillBreakdownItem {
  skill: string;
  studentLevel: number;
  requiredLevel: number;
  gap: number;
  status: 'meets' | 'partial' | 'gap';
  rationale?: string;
}

interface Recommendation {
  priority: 'high' | 'medium' | 'low';
  text: string;
  resource: string | null;
}

interface RadarData {
  axes: string[];
  studentScores: number[];
  requiredScores: number[];
}

interface GapAnalysis {
  id: string;
  pathwayId: string;
  pathwayName: string;
  status: 'queued' | 'processing' | 'complete' | 'error';
  overallMatch: number | null;
  readinessLevel: string | null;
  summary: string | null;
  strengths: string[];
  gaps: string[];
  skillBreakdown: SkillBreakdownItem[];
  recommendations: Recommendation[];
  radarData: RadarData;
  timelineEst: string | null;
  autoGenerated: boolean;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

function matchColor(pct: number | null) {
  if (pct === null) return 'var(--text-muted)';
  if (pct >= 70) return 'var(--success, #15803d)';
  if (pct >= 45) return 'var(--warning, #b45309)';
  return 'var(--error, #dc2626)';
}

function readinessLabel(level: string | null, pct: number | null): string {
  if (level === 'strong_candidate') return 'Strong candidate';
  if (level === 'ready') return 'Ready to apply';
  if (level === 'building') return 'Building readiness';
  if (level === 'early_stage') return 'Early stage — keep building';
  if (pct !== null) {
    if (pct >= 70) return 'Strong candidate';
    if (pct >= 45) return 'Building readiness';
    return 'Early stage — keep building';
  }
  return '';
}

// ─── Analysis Panel ────────────────────────────────────────────────────────────

interface AnalysisPanelProps {
  analysis: GapAnalysis;
  pathway: Pathway;
  onRefresh: (pathwayId: string) => void;
}

function AnalysisPanel({ analysis, pathway, onRefresh }: AnalysisPanelProps) {
  const matchedPrograms = pathway.corePrograms
    ? programs.filter(p => pathway.corePrograms!.includes(p.id)).slice(0, 4)
    : programs.filter(p => p.category?.toLowerCase().includes((pathway.track || '').toLowerCase().split('/')[0]?.trim() || '')).slice(0, 4);

  if (analysis.status === 'queued' || analysis.status === 'processing') {
    return (
      <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-2xl)' }}>
        <div style={{ fontSize: '2rem', marginBottom: 'var(--sp-md)' }}>🧠</div>
        <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-lg)', fontWeight: 700, marginBottom: '0.5rem' }}>Analyzing your profile…</h3>
        <p style={{ color: 'var(--text-muted)', fontSize: 'var(--text-sm)', marginBottom: 'var(--sp-lg)' }}>
          Claude is reading your full profile and reasoning about your readiness for <strong>{pathway.name}</strong>.
          This usually takes 30–60 seconds.
        </p>
        <div style={{ height: 6, background: 'var(--surface-2)', borderRadius: 99, overflow: 'hidden', maxWidth: 300, margin: '0 auto var(--sp-md)' }}>
          <div style={{ height: '100%', width: '60%', background: 'var(--brand-500)', borderRadius: 99, animation: 'gapPulse 2s ease-in-out infinite' }} />
        </div>
        <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)' }}>
          Status: {analysis.status}
        </p>
      </div>
    );
  }

  if (analysis.status === 'error') {
    return (
      <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-xl)' }}>
        <div style={{ fontSize: '1.5rem', marginBottom: '0.5rem' }}>⚠️</div>
        <p style={{ color: 'var(--error, #dc2626)', fontWeight: 600, marginBottom: '0.5rem' }}>Analysis failed</p>
        <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', marginBottom: 'var(--sp-md)' }}>{analysis.error}</p>
        <button className="btn btn-primary btn-sm" onClick={() => onRefresh(pathway.id)}>Try Again</button>
      </div>
    );
  }

  // Complete
  return (
    <div>
      {/* Summary card — first, most prominent */}
      <div className="card" style={{ marginBottom: 'var(--sp-md)', background: 'linear-gradient(135deg, rgba(154,184,46,0.06) 0%, var(--surface) 60%)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: '2.5rem', fontWeight: 800, color: matchColor(analysis.overallMatch), lineHeight: 1 }}>
              {analysis.overallMatch}%
            </div>
            <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', marginTop: '0.25rem' }}>Match</div>
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 'var(--text-xs)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: matchColor(analysis.overallMatch), marginBottom: '0.25rem' }}>
              {readinessLabel(analysis.readinessLevel, analysis.overallMatch)}
            </div>
            <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>
              {analysis.timelineEst && `Timeline: ${analysis.timelineEst}`}
              {analysis.autoGenerated && <span style={{ marginLeft: '0.5rem', background: 'var(--surface-2)', borderRadius: 4, padding: '1px 5px' }}>auto</span>}
            </div>
          </div>
        </div>
        <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-default)', lineHeight: 1.65 }}>
          {analysis.summary}
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.5fr', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
        {/* Strengths */}
        {analysis.strengths.length > 0 && (
          <div className="card">
            <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--success, #15803d)', marginBottom: 'var(--sp-sm)' }}>
              ✓ Strengths
            </h3>
            <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.375rem' }}>
              {analysis.strengths.map((s, i) => (
                <li key={i} style={{ fontSize: 'var(--text-xs)', color: 'var(--text-default)', lineHeight: 1.5 }}>{s}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Gaps */}
        {analysis.gaps.length > 0 && (
          <div className="card">
            <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--error, #dc2626)', marginBottom: 'var(--sp-sm)' }}>
              ↑ Areas to Develop
            </h3>
            <ul style={{ margin: 0, paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.375rem' }}>
              {analysis.gaps.map((g, i) => (
                <li key={i} style={{ fontSize: 'var(--text-xs)', color: 'var(--text-default)', lineHeight: 1.5 }}>{g}</li>
              ))}
            </ul>
          </div>
        )}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.5fr', gap: 'var(--sp-md)', marginBottom: 'var(--sp-md)' }}>
        {/* Radar */}
        {analysis.radarData?.axes?.length > 2 && (
          <div className="card">
            <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--text-muted)', marginBottom: 'var(--sp-sm)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
              Skills Radar
            </h3>
            <RadarChart
              axes={analysis.radarData.axes}
              studentScores={analysis.radarData.studentScores}
              requiredScores={analysis.radarData.requiredScores}
            />
          </div>
        )}

        {/* Skill breakdown */}
        {analysis.skillBreakdown.length > 0 && (
          <div className="card">
            <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--text-strong)', marginBottom: 'var(--sp-sm)' }}>
              Skill Breakdown
            </h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr auto auto', gap: '0.4rem 0.75rem', alignItems: 'center', fontSize: '0.7rem' }}>
              <div style={{ fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Skill</div>
              <div style={{ fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Level</div>
              <div style={{ fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Req</div>
              <div style={{ fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Status</div>
              {analysis.skillBreakdown.slice(0, 8).map((item, i) => (
                <Fragment key={i}>
                  <div style={{ color: 'var(--text-default)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 130 }} title={item.skill}>
                    {item.skill.length > 22 ? item.skill.slice(0, 20) + '…' : item.skill}
                  </div>
                  <div style={{ height: 7, background: 'var(--surface-2)', borderRadius: 99, overflow: 'hidden' }}>
                    <div style={{
                      height: '100%',
                      width: `${Math.round((item.studentLevel || 0) * 100)}%`,
                      background: item.status === 'meets' ? 'var(--success, #15803d)' : item.status === 'partial' ? 'var(--warning, #b45309)' : 'var(--error, #dc2626)',
                      borderRadius: 99,
                    }} />
                  </div>
                  <div style={{ color: 'var(--text-muted)', textAlign: 'center' }}>{Math.round((item.requiredLevel || 0) * 100)}%</div>
                  <div style={{
                    fontSize: '0.6rem', fontWeight: 700, textTransform: 'capitalize',
                    color: item.status === 'meets' ? 'var(--success, #15803d)' : item.status === 'partial' ? 'var(--warning, #b45309)' : 'var(--error, #dc2626)',
                  }}>
                    {item.status}
                  </div>
                </Fragment>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Recommendations */}
      {analysis.recommendations.length > 0 && (
        <div className="card" style={{ marginBottom: 'var(--sp-md)' }}>
          <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--text-strong)', marginBottom: 'var(--sp-md)' }}>
            Recommendations
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-sm)' }}>
            {analysis.recommendations.map((rec, i) => (
              <div key={i} style={{
                display: 'flex', gap: '0.75rem', padding: 'var(--sp-sm)',
                background: rec.priority === 'high' ? 'rgba(220,38,38,0.05)' : rec.priority === 'medium' ? 'rgba(251,191,36,0.08)' : 'var(--surface)',
                borderRadius: 'var(--radius-md)',
                border: `1px solid ${rec.priority === 'high' ? 'rgba(185,28,28,0.12)' : rec.priority === 'medium' ? 'rgba(180,83,9,0.12)' : 'var(--border)'}`,
              }}>
                <div style={{
                  width: 20, height: 20, borderRadius: '50%', flexShrink: 0,
                  background: rec.priority === 'high' ? 'var(--error, #dc2626)' : rec.priority === 'medium' ? 'var(--warning, #b45309)' : 'var(--text-faint)',
                  color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: '0.55rem', fontWeight: 800, textTransform: 'uppercase', marginTop: '0.125rem',
                }}>
                  {rec.priority[0].toUpperCase()}
                </div>
                <div>
                  <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-default)', lineHeight: 1.55 }}>{rec.text}</p>
                  {rec.resource && (
                    <a href={rec.resource} target="_blank" rel="noopener noreferrer" style={{ fontSize: 'var(--text-xs)', color: 'var(--brand-700)', textDecoration: 'underline', marginTop: '0.25rem', display: 'inline-block' }}>
                      Learn more ↗
                    </a>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Matched programs */}
      <div className="card">
        <h3 style={{ fontFamily: 'Plus Jakarta Sans, sans-serif', fontSize: 'var(--text-base)', fontWeight: 700, color: 'var(--text-strong)', marginBottom: 'var(--sp-md)' }}>
          Programs Aligned with {pathway.shortName || pathway.name}
        </h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.625rem' }}>
          {(matchedPrograms.length > 0 ? matchedPrograms : programs.slice(0, 4)).map(p => (
            <div key={p.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.5rem 0', borderBottom: '1px solid var(--border)' }}>
              <div>
                <div style={{ fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--text-strong)' }}>{p.shortName || p.name}</div>
                <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>{p.category}</div>
              </div>
              <a href={p.applicationUrl} target="_blank" rel="noopener noreferrer" className="btn btn-ghost btn-sm">Apply ↗</a>
            </div>
          ))}
        </div>
        <Link to="/opportunities" className="btn btn-outline btn-sm btn-block" style={{ marginTop: 'var(--sp-md)' }}>
          Browse all {programs.length} programs →
        </Link>
      </div>

      <div style={{ marginTop: 'var(--sp-md)', display: 'flex', gap: 'var(--sp-sm)', alignItems: 'center' }}>
        <button onClick={() => onRefresh(pathway.id)} className="btn btn-ghost btn-sm">
          ↺ Re-run analysis
        </button>
        <Link to="/profile" className="btn btn-ghost btn-sm">Update skills →</Link>
        <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)' }}>
          {analysis.updatedAt ? `Last run: ${new Date(analysis.updatedAt).toLocaleDateString()}` : ''}
        </span>
      </div>
    </div>
  );
}

// ─── Main Page ─────────────────────────────────────────────────────────────────

// Minimal DB pathway shape compatible with what AnalysisPanel expects from Pathway
interface DbPathway {
  id: string;
  name: string;
  shortName?: string;
  track?: string;
  description?: string;
  corePrograms?: string[];
  skills?: { name: string; weight: number; category: string }[];
}

export default function PathwayGap() {
  const { id } = useParams<{ id: string }>();
  getCurrentUser(); // auth guard
  const token = localStorage.getItem('cdp_token');

  const [selectedPathwayId, setSelectedPathwayId] = useState(id || pathways[0]?.id || '');
  const [analyses, setAnalyses] = useState<GapAnalysis[]>([]);
  const [loadingAnalyses, setLoadingAnalyses] = useState(true);
  const [runningAnalysis, setRunningAnalysis] = useState(false);
  const [pollingId, setPollingId] = useState<string | null>(null);
  const [runError, setRunError] = useState<string | null>(null);
  // DB pathway fallback: loaded when selectedPathwayId is not found in static JSON
  const [dbPathway, setDbPathway] = useState<DbPathway | null>(null);

  const staticPathway = pathways.find(p => p.id === selectedPathwayId);
  const selectedPathway = (staticPathway || dbPathway || pathways[0]) as unknown as Pathway;
  const activeAnalysis = analyses.find(a => a.pathwayId === selectedPathwayId) || null;

  useEffect(() => { if (id) setSelectedPathwayId(id); }, [id]);

  // Fetch DB pathway when selected ID not in static list
  useEffect(() => {
    if (staticPathway) { setDbPathway(null); return; }
    if (!selectedPathwayId || !token) return;
    fetch(`${API_BASE}/api/cdp/pathways/${selectedPathwayId}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (data?.pathway) {
          const pw = data.pathway;
          setDbPathway({
            id: pw.id,
            name: pw.title,
            shortName: pw.short_name,
            track: pw.career_field,
            description: pw.description,
            skills: (pw.requirements?.skills || []).map((s: string) => ({ name: s, weight: 3, category: 'General' })),
          });
        }
      })
      .catch(() => {});
  }, [selectedPathwayId, staticPathway, token]);

  // Load all analyses
  const loadAnalyses = useCallback(async () => {
    try {
      const res = await fetch(`${API_BASE}/api/cdp/gap-analyses`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.ok) {
        setAnalyses(data.analyses || []);
        // If any analysis is stuck in-progress from a previous session, start polling it
        const inProgress = (data.analyses || []).find(
          (a: { status: string; id: string }) => a.status === 'queued' || a.status === 'processing'
        );
        if (inProgress) setPollingId(inProgress.id);
      }
    } catch {}
    setLoadingAnalyses(false);
  }, [token]);

  useEffect(() => { loadAnalyses(); }, [loadAnalyses]);

  // Poll for in-progress analysis
  useEffect(() => {
    if (!pollingId) return;
    const interval = setInterval(async () => {
      try {
        const res = await fetch(`${API_BASE}/api/cdp/gap-analysis/status/${pollingId}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        if (data.status === 'complete' || data.status === 'error') {
          // Update the analysis in state
          setAnalyses(prev => {
            const without = prev.filter(a => a.pathwayId !== data.pathwayId);
            return [...without, data];
          });
          setPollingId(null);
          setRunningAnalysis(false);
          clearInterval(interval);
        }
      } catch {}
    }, 3000);
    return () => clearInterval(interval);
  }, [pollingId, token]);

  const runAnalysis = async (pathwayId: string, force = false) => {
    setRunningAnalysis(true);
    setRunError(null);
    try {
      const res = await fetch(`${API_BASE}/api/cdp/gap-analysis/run`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ pathway_id: pathwayId, force }),
      });
      const data = await res.json();
      if (!data.ok) throw new Error(data.error || 'Failed to start analysis');

      if (data.status === 'complete' && data.cached) {
        // Already cached — fetch full detail
        const detailRes = await fetch(`${API_BASE}/api/cdp/gap-analysis/${data.job_id}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const detail = await detailRes.json();
        if (detail.ok) {
          setAnalyses(prev => {
            const without = prev.filter(a => a.pathwayId !== pathwayId);
            return [...without, detail.analysis];
          });
        }
        setRunningAnalysis(false);
      } else {
        // Queued/processing — add optimistic entry and start polling
        const optimistic: GapAnalysis = {
          id: data.job_id,
          pathwayId,
          pathwayName: selectedPathway.name,
          status: data.status,
          overallMatch: null,
          readinessLevel: null,
          summary: null,
          strengths: [],
          gaps: [],
          skillBreakdown: [],
          recommendations: [],
          radarData: { axes: [], studentScores: [], requiredScores: [] },
          timelineEst: null,
          autoGenerated: false,
          error: null,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };
        setAnalyses(prev => {
          const without = prev.filter(a => a.pathwayId !== pathwayId);
          return [...without, optimistic];
        });
        setPollingId(data.job_id);
      }
    } catch {
      setRunError('Failed to start analysis. Please try again.');
      setRunningAnalysis(false);
    }
  };

  return (
    <>
      <Nav />
      <main id="main">
        <div className="page-header">
          <div className="page-container">
            <h1>Gap Analysis</h1>
            <p>AI-powered career pathway analysis — Claude reads your full profile and reasons about your readiness</p>
          </div>
        </div>

        <div className="page-container" style={{ padding: 'var(--sp-lg) 1.25rem var(--sp-2xl)' }}>
          {!loadingAnalyses && analyses.length === 0 && !activeAnalysis && (
            <div style={{ background: 'rgba(154,184,46,0.06)', border: '1px solid rgba(154,184,46,0.2)', borderRadius: 'var(--radius-lg)', padding: 'var(--sp-md)', marginBottom: 'var(--sp-lg)', fontSize: 'var(--text-sm)', color: 'var(--text-default)', lineHeight: 1.6 }}>
              <strong>How it works:</strong> Select a pathway and click "Run Analysis" — Claude reads your full profile and reasoning about how well you match this career path. Each analysis takes ~45 seconds and is cached for 7 days.
            </div>
          )}

          <div className="gap-layout" style={{ display: 'grid', gridTemplateColumns: '220px 1fr', gap: 'var(--sp-xl)', alignItems: 'start' }}>

            {/* ── Left sidebar: analysis list ── */}
            <div>
              <div style={{ marginBottom: 'var(--sp-md)' }}>
                <div style={{ fontSize: 'var(--text-xs)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 'var(--sp-sm)' }}>
                  Your Analyses
                </div>

                {loadingAnalyses ? (
                  <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>Loading…</p>
                ) : analyses.length === 0 ? (
                  <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', lineHeight: 1.5 }}>No analyses yet. Select a pathway and run your first analysis.</p>
                ) : (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.375rem' }}>
                    {analyses.map(a => (
                      <button
                        key={a.id}
                        onClick={() => setSelectedPathwayId(a.pathwayId)}
                        style={{
                          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                          width: '100%', textAlign: 'left', padding: '0.5rem 0.625rem',
                          borderRadius: 'var(--radius-md)',
                          border: a.pathwayId === selectedPathwayId ? '1px solid var(--brand-500)' : '1px solid var(--border)',
                          background: a.pathwayId === selectedPathwayId ? 'rgba(154,184,46,0.08)' : 'var(--surface)',
                          cursor: 'pointer', fontSize: 'var(--text-xs)',
                        }}
                      >
                        <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: 'var(--text-default)', fontWeight: a.pathwayId === selectedPathwayId ? 600 : 400, maxWidth: 130 }}>
                          {a.pathwayName}
                        </span>
                        {a.status === 'complete' && a.overallMatch !== null ? (
                          <span style={{ fontWeight: 700, color: matchColor(a.overallMatch), fontSize: '0.65rem', flexShrink: 0, marginLeft: '0.25rem' }}>
                            {a.overallMatch}%
                          </span>
                        ) : a.status === 'processing' || a.status === 'queued' ? (
                          <span style={{ fontSize: '0.6rem', color: '#b45309', flexShrink: 0 }}>…</span>
                        ) : null}
                      </button>
                    ))}
                  </div>
                )}
              </div>

              <div style={{ borderTop: '1px solid var(--border)', paddingTop: 'var(--sp-md)' }}>
                <div style={{ fontSize: 'var(--text-xs)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 'var(--sp-sm)' }}>
                  Select Pathway
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  {pathways.map(p => (
                    <button
                      key={p.id}
                      onClick={() => setSelectedPathwayId(p.id)}
                      style={{
                        textAlign: 'left', padding: '0.375rem 0.5rem',
                        borderRadius: 'var(--radius-sm)',
                        border: 'none',
                        background: p.id === selectedPathwayId ? 'var(--brand-50)' : 'transparent',
                        color: p.id === selectedPathwayId ? 'var(--brand-700)' : 'var(--text-muted)',
                        fontSize: '0.7rem', fontWeight: p.id === selectedPathwayId ? 700 : 400,
                        cursor: 'pointer', width: '100%',
                      }}
                    >
                      {p.shortName || p.name}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* ── Right: pathway info + analysis ── */}
            <div>
              {/* Pathway header */}
              <div className="card" style={{ marginBottom: 'var(--sp-md)' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 'var(--sp-md)' }}>
                  <div>
                    <div className="badge badge-lime" style={{ marginBottom: 'var(--sp-sm)' }}>{selectedPathway?.track}</div>
                    <h2 style={{ fontSize: 'var(--text-xl)', color: 'var(--text-strong)', marginBottom: '0.375rem' }}>{selectedPathway?.name}</h2>
                    <p style={{ color: 'var(--text-muted)', fontSize: 'var(--text-sm)', lineHeight: 1.6, marginBottom: 0 }}>{selectedPathway?.description}</p>
                  </div>
                  {!activeAnalysis || activeAnalysis.status === 'error' ? (
                    <button
                      className="btn btn-primary btn-sm"
                      onClick={() => runAnalysis(selectedPathwayId)}
                      disabled={runningAnalysis}
                      style={{ flexShrink: 0 }}
                    >
                      {runningAnalysis ? 'Starting…' : '▶ Run Analysis'}
                    </button>
                  ) : activeAnalysis.status === 'complete' ? (
                    <button
                      className="btn btn-ghost btn-sm"
                      onClick={() => runAnalysis(selectedPathwayId, true)}
                      disabled={runningAnalysis}
                      style={{ flexShrink: 0 }}
                    >
                      ↺ Re-run
                    </button>
                  ) : null}
                </div>
              </div>

              {runError && (
                <div style={{ color: 'var(--error, #dc2626)', fontSize: 'var(--text-sm)', padding: '0.5rem 0.75rem', background: 'rgba(220,38,38,0.06)', borderRadius: 'var(--radius-md)', marginBottom: 'var(--sp-md)', border: '1px solid rgba(220,38,38,0.2)' }}>
                  {runError}
                </div>
              )}

              {/* Analysis output or prompt */}
              {!activeAnalysis ? (
                <div className="card" style={{ textAlign: 'center', padding: 'var(--sp-2xl)', color: 'var(--text-muted)' }}>
                  <div style={{ fontSize: '2rem', marginBottom: 'var(--sp-md)', opacity: 0.4 }}>🧠</div>
                  <p style={{ fontSize: 'var(--text-sm)', marginBottom: 'var(--sp-md)' }}>
                    No analysis yet for <strong>{selectedPathway?.name}</strong>
                  </p>
                  <button
                    className="btn btn-primary"
                    onClick={() => runAnalysis(selectedPathwayId)}
                    disabled={runningAnalysis}
                  >
                    {runningAnalysis ? 'Starting analysis…' : 'Run Analysis'}
                  </button>
                  <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-faint)', marginTop: 'var(--sp-sm)' }}>
                    Usually takes 30–60 seconds
                  </p>
                </div>
              ) : (
                <AnalysisPanel
                  analysis={activeAnalysis}
                  pathway={selectedPathway}
                  onRefresh={(pId) => runAnalysis(pId, true)}
                />
              )}
            </div>
          </div>
        </div>
      </main>

      <style>{`
        @media (max-width: 700px) {
          .gap-layout { grid-template-columns: 1fr !important; }
        }
        @keyframes gapPulse {
          0%, 100% { transform: translateX(-40%); }
          50% { transform: translateX(140%); }
        }
      `}</style>
    </>
  );
}
