// ─── Core Types for LLI CDP App ───────────────────────────────────────────────

export interface User {
  uid: string;
  email: string;
  firstName?: string;
  lastName?: string;
  onboardingComplete?: boolean;
}

export interface StudentProfile {
  firstName: string;
  lastName: string;
  school: string;
  year: string;
  major: string;
  gradYear: string;
  email: string;
  createdAt: string;
  updatedAt: string;
}

export type ExperienceType = 'work' | 'research' | 'education' | 'leadership' | 'volunteer' | 'other';

export interface ExperienceEntry {
  id: string;
  type: ExperienceType;
  title: string;
  org: string;
  duration: string;        // human-readable: "May 2023 – Aug 2023"
  startDate?: string;      // "YYYY-MM" for sorting
  endDate?: string | null; // null = present/ongoing
  description?: string;
  skills?: string[];
}

export interface StudentData {
  profile: StudentProfile;
  interests: string[];
  skills: string[];
  goals: string[];
  targetTimeline: string;
  gpa: number | null;
  experienceLevel: string;
  profileCompleteness: number;
  savedPrograms: string[];
  gapAnalyses: GapAnalysis[];
  resumeUploaded: boolean;
  experience?: ExperienceEntry[];
}

export interface GapAnalysis {
  id: string;
  pathwayId: string;
  createdAt: string;
  overallMatch: number;
  radarData: RadarData;
  skillBreakdown: SkillBreakdownItem[];
  recommendations: Recommendation[];
}

export interface RadarData {
  axes: string[];
  studentScores: number[];
  requiredScores: number[];
}

export interface SkillBreakdownItem {
  skill: string;
  studentLevel: number;
  requiredLevel: number;
  gap: number;
  status: 'meets' | 'partial' | 'gap';
}

export interface Recommendation {
  priority: 'high' | 'medium' | 'low';
  text: string;
  resource?: string;
}

export interface ProgramTags {
  career_stage?: string[];
  benefits?: string[];
  duration?: string[];
  location_type?: string[];
  focus_type?: string[];
  special_eligibility?: string[];
  keywords?: string[];
}

export interface Program {
  id: string;
  name: string;
  shortName: string;
  category: string;
  type: string;
  eligibility: {
    level: string[];
    citizenship: string[];
    gpa?: number;
    notes?: string;
  };
  duration: {
    weeks: number | null;
    terms: string[];
  };
  compensation: {
    paid: boolean;
    stipend: string;
    housing?: string;
    travel?: string;
  };
  locations: string[];
  researchAreas: string[];
  deadlines: Record<string, string>;
  applicationUrl: string;
  applicationPlatform: string;
  keyFacts: string[];
  lliBridgeNote: string;
  tags?: ProgramTags | null;
  sector?: string;
}

export interface Pathway {
  id: string;
  name: string;
  shortName: string;
  track: string;
  targetLevel: string[];
  targetPrograms: string[];
  description: string;
  timeToReady: string;
  skills: PathwaySkill[];
  radarAxes?: RadarAxis[];
  recommendedCourses?: string[];
  careerOutcomes?: string[];
  corePrograms?: string[];
}

export interface PathwaySkill {
  name: string;
  weight: number;
  category: string;
}

export interface RadarAxis {
  name: string;
  skills: string[];
  weight: number;
}

// ─── Resume Management v2 ─────────────────────────────────────────────────────

export interface ResumeParsedSummary {
  skills_count: number;
  experience_count: number;
  skills: string[];
}

export interface ResumeRecord {
  id: string;
  label: string;
  original_name: string;
  file_size: number;
  mime_type?: string;
  status: 'processing' | 'parsed' | 'error';
  parsed_summary: ResumeParsedSummary | null;
  error: string | null;
  created_at: string;
}

// ─── Agentic Gap Analysis v2 ──────────────────────────────────────────────────

export interface SkillBreakdownItemV2 extends SkillBreakdownItem {
  rationale: string;
}

export interface GapAnalysisV2 {
  id: string;
  pathwayId: string;
  pathwayName: string;
  status: 'queued' | 'processing' | 'complete' | 'error';
  overallMatch: number | null;
  readinessLevel: 'early_stage' | 'building' | 'ready' | 'strong_candidate' | null;
  summary: string | null;
  strengths: string[];
  gaps: string[];
  skillBreakdown: SkillBreakdownItemV2[];
  recommendations: Recommendation[];
  radarData: RadarData;
  timelineEst: string | null;
  autoGenerated: boolean;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}
